function result = forwardPassiveDoublet(qLower, geometry, options)
%FORWARDPASSIVEDOUBLET Solve the complete single-actuated doublet closure.
if nargin < 3
    options = struct();
end

geometry = duallink5.model.validateGeometry(geometry);
qLower = validateQ(qLower);
options = validateOptions(options, geometry);
result = invalidResult(geometry, qLower, "UNINITIALIZED");

lowerOptions = struct( ...
    'branchMode', options.lowerBranchMode, ...
    'branchId', options.lowerBranchId, ...
    'collisionProfile', options.collisionProfile);
if options.lowerBranchMode == "continuous"
    lowerOptions.previousPose = options.previousPose.lower;
    lowerOptions.maxContinuityCost = Inf;
end
lower = duallink5.kinematics.forwardFiveBar( ...
    qLower, geometry, lowerOptions);
result.lower = lower;
if ~lower.quality.valid
    result.quality.statusCode = lower.quality.statusCode;
    result.quality.closureStatusCode = lower.quality.statusCode;
    result.upper.quality.statusCode = lower.quality.statusCode;
    result.quality.theoreticallyReachable = ...
        lower.quality.statusCode ~= "UNREACHABLE_CLOSURE";
    result.quality.continuityCost = lower.quality.continuityCost;
    return
end

p = lower.points;
Aupper = p.D + (p.E - p.A);
Cupper = p.E + (p.D - p.C);
[candidates, closureStatus] = passiveClosure( ...
    Aupper, Cupper, geometry.links.link5, geometry.links.link2);
result.quality.closureStatusCode = closureStatus;
result.passiveCandidates = candidates;
if isempty(candidates)
    result.quality.statusCode = closureStatus;
    result.upper.quality.statusCode = closureStatus;
    return
end
if any([candidates.closureResidual] > geometry.tolerance.residual)
    result.quality.statusCode = "NUMERICAL_CLOSURE_FAILURE";
    result.quality.closureStatusCode = "NUMERICAL_CLOSURE_FAILURE";
    result.upper.quality.statusCode = "NUMERICAL_CLOSURE_FAILURE";
    result.passiveCandidates = emptyCandidates();
    return
end
result.quality.theoreticallyReachable = true;

[candidate, continuityCost] = selectCandidate( ...
    candidates, p.G, options);
result.quality.continuityCost = continuityCost;
result.quality.passiveBranchId = candidate.branchId;
result.quality.passiveOrientationSign = candidate.orientationSign;

G = candidate.G;
upper = buildUpperPose(Aupper, Cupper, G, lower, geometry, candidate);
result.upper = upper;
result.points = struct('G', G, 'Aupper', Aupper, 'Cupper', Cupper);
result.sharedLink = lower.sharedLink;
result.residuals = geometricResiduals(result, geometry);
result.quality.closureResidual = candidate.closureResidual;
if continuityCost > options.maxContinuityCost
    result.quality.statusCode = "BRANCH_DISCONTINUITY";
    return
end
upper = duallink5.validation.assessFiveBarPose( ...
    upper, geometry, options.collisionProfile);
result.upper = upper;
if ~upper.quality.valid
    result.quality.statusCode = upper.quality.statusCode;
    return
end
if options.collisionProfile ~= "none"
    clearance = parallelSharedDistance(lower.points);
    result.quality.parallelSharedClearance = clearance;
    if clearance <= geometry.collision.parallelSharedClearance
        result.quality.statusCode = "PARALLEL_SHARED_COLLISION";
        return
    end
end

result.quality.valid = true;
result.quality.statusCode = "OK";
end

function q = validateQ(q)
if ~(isnumeric(q) && isreal(q) && isequal(size(q), [1, 2]) && ...
        all(isfinite(q)))
    error('duallink5:kinematics:InvalidPassiveDoubletInput', ...
        'qLower must be a finite real numeric 1x2 vector.');
end
q = full(double(q));
end

function options = validateOptions(input, geometry)
if ~isstruct(input) || ~isscalar(input)
    invalidOptions('options must be a scalar struct.');
end
supported = {'collisionProfile', 'lowerBranchMode', ...
    'lowerBranchId', 'previousPose', 'maxContinuityCost'};
if ~all(ismember(fieldnames(input), supported))
    invalidOptions('options contains an unsupported field.');
end

options = struct( ...
    'collisionProfile', optionValue(input, 'collisionProfile', ...
        "centerline"), ...
    'lowerBranchMode', optionValue(input, 'lowerBranchMode', "fixed"), ...
    'lowerBranchId', optionValue(input, 'lowerBranchId', ...
        geometry.assembly.defaultBranch), ...
    'previousPose', optionValue(input, 'previousPose', []), ...
    'maxContinuityCost', optionValue(input, 'maxContinuityCost', Inf));

try
    options.collisionProfile = string(options.collisionProfile);
    options.lowerBranchMode = string(options.lowerBranchMode);
catch
    invalidOptions('text options must be scalar text.');
end
if ~isscalar(options.collisionProfile) || ...
        ismissing(options.collisionProfile) || ...
        ~ismember(options.collisionProfile, ...
        ["none", "centerline", "physicalClearance"])
    invalidOptions('collisionProfile is invalid.');
end
if ~isscalar(options.lowerBranchMode) || ...
        ismissing(options.lowerBranchMode) || ...
        ~ismember(options.lowerBranchMode, ["fixed", "continuous"])
    invalidOptions('lowerBranchMode must be fixed or continuous.');
end
if ~(isnumeric(options.lowerBranchId) && ...
        isreal(options.lowerBranchId) && ...
        isscalar(options.lowerBranchId) && ...
        isfinite(options.lowerBranchId) && ...
        ismember(double(options.lowerBranchId), [-1, 1]))
    invalidOptions('lowerBranchId must be -1 or +1.');
end
options.lowerBranchId = int8(options.lowerBranchId);
if ~(isnumeric(options.maxContinuityCost) && ...
        isreal(options.maxContinuityCost) && ...
        isscalar(options.maxContinuityCost) && ...
        ~isnan(options.maxContinuityCost) && ...
        options.maxContinuityCost > 0)
    invalidOptions('maxContinuityCost must be positive or Inf.');
end
options.maxContinuityCost = double(options.maxContinuityCost);

if ~isempty(options.previousPose) && ...
        ~validPreviousPose(options.previousPose)
    invalidOptions('previousPose must be a passive-doublet result.');
end
if options.lowerBranchMode == "continuous" && ...
        isempty(options.previousPose)
    invalidOptions('continuous mode requires previousPose.');
end
end

function valid = validPreviousPose(previous)
valid = isstruct(previous) && isscalar(previous) && ...
    isfield(previous, 'points') && isstruct(previous.points) && ...
    isscalar(previous.points) && isfield(previous.points, 'G') && ...
    validPoint(previous.points.G) && ...
    isfield(previous, 'lower') && isstruct(previous.lower) && ...
    isscalar(previous.lower) && isfield(previous.lower, 'points') && ...
    isstruct(previous.lower.points) && ...
    isscalar(previous.lower.points) && ...
    isfield(previous.lower.points, 'D') && ...
    validPoint(previous.lower.points.D);
end

function valid = validPoint(point)
valid = isnumeric(point) && isreal(point) && ...
    isvector(point) && numel(point) == 2 && all(isfinite(point));
end

function value = optionValue(options, name, defaultValue)
if isfield(options, name)
    value = options.(name);
else
    value = defaultValue;
end
end

function invalidOptions(message)
error('duallink5:kinematics:InvalidPassiveDoubletOptions', message);
end

function [candidates, status] = passiveClosure(A, C, radiusA, radiusC)
candidates = emptyCandidates();
delta = C - A;
distance = norm(delta);
targets = [abs(radiusA - radiusC), radiusA + radiusC];
scale = max([distance, targets, radiusA, radiusC]);
tangentTolerance = 32 * eps(scale);
equalRadii = abs(radiusA - radiusC) <= tangentTolerance;
coincidentTolerance = 32 * eps(max([radiusA, radiusC]));

if equalRadii && distance <= coincidentTolerance
    status = "COINCIDENT_CIRCLES";
    return
end
if distance < targets(1) - tangentTolerance || ...
        distance > targets(2) + tangentTolerance
    status = "UNREACHABLE_PASSIVE_CLOSURE";
    return
end

direction = delta / distance;
along = (radiusA^2 - radiusC^2 + distance^2) / (2 * distance);
if ~equalRadii && abs(distance - targets(1)) <= tangentTolerance
    G = A + along * direction;
    candidates = makeCandidate(G, int8(0), A, C, radiusA, radiusC);
    status = "INTERNAL_TANGENCY";
    return
end
if abs(distance - targets(2)) <= tangentTolerance
    G = A + along * direction;
    candidates = makeCandidate(G, int8(0), A, C, radiusA, radiusC);
    status = "EXTERNAL_TANGENCY";
    return
end

height = sqrt(max(0, radiusA^2 - along^2));
normal = [-direction(2); direction(1)];
first = A + along * direction + height * normal;
second = A + along * direction - height * normal;
firstSign = int8(sign(cross2(delta, first - A)));
secondSign = int8(sign(cross2(delta, second - A)));
candidates = [ ...
    makeCandidate(first, firstSign, A, C, radiusA, radiusC), ...
    makeCandidate(second, secondSign, A, C, radiusA, radiusC)];
status = "OK";
end

function candidates = emptyCandidates()
candidates = struct( ...
    'G', {}, ...
    'branchId', {}, ...
    'orientationSign', {}, ...
    'closureResidual', {});
end

function candidate = makeCandidate(G, branchId, A, C, radiusA, radiusC)
candidate = struct( ...
    'G', G, ...
    'branchId', branchId, ...
    'orientationSign', branchId, ...
    'closureResidual', max(abs([ ...
        norm(G - A) - radiusA, norm(G - C) - radiusC])));
end

function [candidate, cost] = selectCandidate(candidates, idealG, options)
if options.lowerBranchMode == "continuous"
    reference = options.previousPose.points.G(:);
else
    reference = idealG;
end
costs = arrayfun(@(item) norm(item.G - reference), candidates);
[cost, index] = min(costs);
candidate = candidates(index);
if options.lowerBranchMode == "fixed"
    cost = 0;
end
end

function upper = buildUpperPose(A, C, G, lower, geometry, candidate)
p = lower.points;
upper.points = struct( ...
    'A', A, ...
    'B', G, ...
    'C', C, ...
    'D', p.E, ...
    'E', p.D, ...
    'G', p.B);
upper.sharedLink.start = upper.points.E;
upper.sharedLink.end = upper.points.D;
upper.sharedLink.center = (upper.points.D + upper.points.E) / 2;
direction = upper.sharedLink.end - upper.sharedLink.start;
upper.sharedLink.orientation = atan2(direction(2), direction(1));
upper.quality = struct( ...
    'valid', true, ...
    'branchId', candidate.branchId, ...
    'closureResidual', candidate.closureResidual, ...
    'continuityCost', NaN, ...
    'collisionFree', NaN, ...
    'clearanceModelApplied', false, ...
    'statusCode', "OK");
upper.metadata = struct( ...
    'units', geometry.units, ...
    'convention', geometry.convention, ...
    'geometryVersion', geometry.version);
end

function residuals = geometricResiduals(result, geometry)
lower = result.lower.points;
upper = result.upper.points;
L = geometry.links;

residuals.upperLinks = struct( ...
    'link1', norm(upper.E - upper.A) - L.link1, ...
    'link2', norm(upper.C - upper.B) - L.link2, ...
    'link3', norm(upper.D - upper.C) - L.link3, ...
    'link4', norm(upper.D - upper.E) - L.link4, ...
    'link5', norm(upper.B - upper.A) - L.link5);
residuals.upper = residuals.upperLinks;
span = geometry.parallel.lengths.Palpha1_Palpha4;
residuals.alpha = parallelogramResiduals( ...
    lower.Palpha1, lower.Palpha2, lower.Palpha3, lower.Palpha4, ...
    L.link4, span);
span = geometry.parallel.lengths.Pbeta2_Pbeta3;
residuals.beta = parallelogramResiduals( ...
    lower.Pbeta1, lower.Pbeta2, lower.Pbeta3, lower.Pbeta4, ...
    L.link4, span);
residuals.rigidLines = struct( ...
    'alphaLower', max([ ...
        pointLineDistance(lower.Palpha1, lower.A, lower.E), ...
        pointLineDistance(lower.Palpha4, lower.A, lower.E)]), ...
    'alphaUpper', max([ ...
        pointLineDistance(lower.Palpha2, lower.D, upper.A), ...
        pointLineDistance(lower.Palpha3, lower.D, upper.A)]), ...
    'betaLower', max([ ...
        pointLineDistance(lower.Pbeta2, lower.C, lower.D), ...
        pointLineDistance(lower.Pbeta3, lower.C, lower.D)]), ...
    'betaUpper', max([ ...
        pointLineDistance(lower.Pbeta1, lower.E, upper.C), ...
        pointLineDistance(lower.Pbeta4, lower.E, upper.C)]));
residuals.shared = struct( ...
    'upperDLowerE', norm(upper.D - lower.E), ...
    'upperELowerD', norm(upper.E - lower.D), ...
    'upperGLowerB', norm(upper.G - lower.B), ...
    'selectedGUpperB', norm(result.points.G - upper.B));
residuals.idealSymmetry = struct( ...
    'A', norm(upper.A - (lower.G + lower.B)), ...
    'B', norm(upper.B - lower.G), ...
    'C', norm(upper.C - (lower.G + lower.B - lower.C)), ...
    'D', norm(upper.D - lower.E), ...
    'E', norm(upper.E - lower.D), ...
    'G', norm(upper.G - lower.B));
residuals.maximum = maximumResidual(residuals);
end

function residuals = parallelogramResiduals(p1, p2, p3, p4, width, span)
side12 = p2 - p1;
side23 = p3 - p2;
side34 = p4 - p3;
side41 = p1 - p4;
residuals = struct( ...
    'side12Length', norm(side12) - width, ...
    'side23Length', norm(side23) - span, ...
    'side34Length', norm(side34) - width, ...
    'side41Length', norm(side41) - span, ...
    'oppositeLength12_34', norm(side12) - norm(side34), ...
    'oppositeLength23_41', norm(side23) - norm(side41), ...
    'transmissionParallel', parallelResidual(side12, -side34), ...
    'rigidParallel', parallelResidual(side23, -side41));
residuals.oppositeParallel = max( ...
    residuals.transmissionParallel, residuals.rigidParallel);
end

function value = parallelResidual(first, second)
value = abs(cross2(first, second)) / (norm(first) * norm(second));
end

function distance = pointLineDistance(point, first, second)
direction = second - first;
distance = abs(cross2(direction, point - first)) / norm(direction);
end

function distance = parallelSharedDistance(points)
distance = min([ ...
    pointSegmentDistance(points.Pbeta1, points.E, points.D), ...
    pointSegmentDistance(points.Pbeta2, points.E, points.D), ...
    pointSegmentDistance(points.E, points.Pbeta1, points.Pbeta2), ...
    pointSegmentDistance(points.D, points.Pbeta1, points.Pbeta2)]);
end

function distance = pointSegmentDistance(point, startPoint, endPoint)
segment = endPoint - startPoint;
denominator = dot(segment, segment);
if denominator == 0
    distance = norm(point - startPoint);
    return
end
parameter = dot(point - startPoint, segment) / denominator;
parameter = max(0, min(1, parameter));
distance = norm(point - (startPoint + parameter * segment));
end

function maximum = maximumResidual(residuals)
values = collectNumericScalars(residuals);
values = values(isfinite(values));
if isempty(values)
    maximum = NaN;
else
    maximum = max(abs(values));
end
end

function values = collectNumericScalars(value)
values = zeros(1, 0);
names = fieldnames(value);
for index = 1:numel(names)
    field = value.(names{index});
    if isstruct(field)
        values = [values, collectNumericScalars(field)]; %#ok<AGROW>
    elseif isnumeric(field) && isreal(field) && isscalar(field)
        values(end + 1) = double(field); %#ok<AGROW>
    end
end
end

function value = cross2(first, second)
value = first(1) * second(2) - first(2) * second(1);
end

function result = invalidResult(geometry, qLower, status)
result = struct();
result.lower = struct();
invalidSharedLink = struct( ...
    'start', NaN(2, 1), ...
    'end', NaN(2, 1), ...
    'center', NaN(2, 1), ...
    'orientation', NaN);
invalidQuality = struct( ...
    'valid', false, ...
    'branchId', NaN, ...
    'closureResidual', NaN, ...
    'continuityCost', NaN, ...
    'collisionFree', NaN, ...
    'clearanceModelApplied', false, ...
    'statusCode', string(status));
result.upper = struct( ...
    'points', struct(), ...
    'sharedLink', invalidSharedLink, ...
    'quality', invalidQuality, ...
    'metadata', struct());
result.sharedLink = invalidSharedLink;
result.points = struct('G', NaN(2, 1), ...
    'Aupper', NaN(2, 1), 'Cupper', NaN(2, 1));
result.passiveCandidates = emptyCandidates();
result.residuals = struct('maximum', NaN);
result.quality = struct( ...
    'valid', false, ...
    'theoreticallyReachable', false, ...
    'statusCode', string(status), ...
    'closureStatusCode', string(status), ...
    'passiveBranchId', NaN, ...
    'passiveOrientationSign', NaN, ...
    'closureResidual', NaN, ...
    'continuityCost', NaN, ...
    'parallelSharedClearance', NaN);
result.metadata = struct( ...
    'units', geometry.units, ...
    'convention', geometry.convention, ...
    'geometryVersion', geometry.version, ...
    'qLower', qLower);
end
