classdef TestAssembly < matlab.unittest.TestCase
    properties
        Geometry
        Q
    end

    methods (TestMethodSetup)
        function setup(testCase)
            testDir = fileparts(mfilename('fullpath'));
            projectRoot = fileparts(fileparts(testDir));
            run(fullfile(projectRoot, 'startup.m'));
            testCase.Geometry = duallink5.model.defaultGeometry();
            testCase.Q = deg2rad([85, 52.93]);
        end
    end

    methods (Test)
        function idealSymmetryClosesSharedLink(testCase)
            q.lower = testCase.Q;
            q.upper = testCase.Q;
            assembly = duallink5.kinematics.forwardAssembly( ...
                q, testCase.Geometry, struct('mode', "ideal"));

            testCase.verifyTrue(assembly.quality.valid);
            testCase.verifyLessThan(norm(assembly.symmetryResidual), 1e-10);
            testCase.verifyEqual(assembly.lower.points.E, ...
                assembly.upper.points.D, 'AbsTol', 1e-10);
            testCase.verifyEqual(assembly.lower.points.D, ...
                assembly.upper.points.E, 'AbsTol', 1e-10);
        end

        function fullAssemblyClearanceRejectsFoldedPose(testCase)
            q.lower = deg2rad([180, 68.25]);
            q.upper = q.lower;

            assembly = duallink5.kinematics.forwardAssembly( ...
                q, testCase.Geometry, struct('mode', "ideal"));

            testCase.verifyFalse(assembly.quality.valid);
            testCase.verifyEqual(assembly.quality.statusCode, ...
                "PARALLEL_SHARED_COLLISION");
            testCase.verifyLessThanOrEqual( ...
                assembly.quality.parallelSharedClearance, ...
                testCase.Geometry.collision.parallelSharedClearance);
        end

        function collisionProfileNoneDisablesAssemblyClearance(testCase)
            q.lower = deg2rad([180, 68.25]);
            q.upper = q.lower;

            assembly = duallink5.kinematics.forwardAssembly( ...
                q, testCase.Geometry, ...
                struct('mode', "ideal", 'collisionProfile', "none"));

            testCase.verifyTrue(assembly.quality.valid);
            testCase.verifyEqual(assembly.quality.statusCode, "OK");
        end

        function diagnosticModeReportsPerturbation(testCase)
            q.lower = testCase.Q;
            q.upper = testCase.Q + deg2rad([0.2, -0.1]);
            assembly = duallink5.kinematics.forwardAssembly( ...
                q, testCase.Geometry, struct('mode', "diagnostic"));

            lowerEstimate = assembly.sharedLinkEstimates.lower;
            upperEstimate = assembly.sharedLinkEstimates.upper;
            expected = [upperEstimate.center - lowerEstimate.center; ...
                atan2(sin(upperEstimate.orientation - ...
                lowerEstimate.orientation), ...
                cos(upperEstimate.orientation - ...
                lowerEstimate.orientation))];
            testCase.verifyEqual(assembly.symmetryResidual, expected, ...
                'AbsTol', 1e-12);
            testCase.verifyEqual(assembly.symmetryResidual, ...
                [2.88896613817112e-4; -5.48531152552295e-5; ...
                8.19584059540190e-4], 'AbsTol', 1e-12);
            testCase.verifyGreaterThan(assembly.symmetryResidual(1), 0);
            testCase.verifyLessThan(assembly.symmetryResidual(2), 0);
            testCase.verifyGreaterThan(assembly.symmetryResidual(3), 0);
            testCase.verifyEqual( ...
                assembly.metadata.symmetryResidualUnits, ...
                ["m"; "m"; "rad"]);
            testCase.verifyEqual( ...
                assembly.quality.statusCode, "SHARED_LINK_MISMATCH");
            testCase.verifyFalse(assembly.quality.valid);
            testCase.verifyTrue(assembly.quality.diagnosticAvailable);
            testCase.verifyFalse(isfield(assembly, 'sharedLink'));
            testCase.verifyError( ...
                @() duallink5.kinematics.taskPose( ...
                assembly, struct('kind', "sharedCenter")), ...
                'duallink5:kinematics:AmbiguousDiagnosticTask');
        end

        function taskSpecSelectsCenterAndOffset(testCase)
            q.lower = testCase.Q;
            q.upper = testCase.Q;
            assembly = duallink5.kinematics.forwardAssembly( ...
                q, testCase.Geometry);

            center = duallink5.kinematics.taskPose(assembly, ...
                struct('kind', "sharedCenter", ...
                'includeOrientation', true));
            offset = duallink5.kinematics.taskPose(assembly, ...
                struct('kind', "sharedOffset", 'offset', [10e-3; 0], ...
                'includeOrientation', true));
            marker = duallink5.kinematics.taskPose(assembly, ...
                struct('kind', "marker", 'offset', [10e-3; 0], ...
                'orientationOffset', 0.2, ...
                'includeOrientation', true));

            testCase.verifyEqual(center.position, ...
                assembly.sharedLink.center, 'AbsTol', 1e-12);
            testCase.verifyEqual( ...
                norm(offset.position - center.position), 10e-3, ...
                'AbsTol', 1e-12);
            testCase.verifyEqual( ...
                marker.position, offset.position, 'AbsTol', 1e-12);
            testCase.verifyEqual( ...
                atan2(sin(marker.orientation - center.orientation), ...
                cos(marker.orientation - center.orientation)), ...
                0.2, 'AbsTol', 1e-12);
        end

        function previousAssemblyControlsBothContinuousBranches(testCase)
            q.lower = testCase.Q;
            q.upper = testCase.Q;
            previous = duallink5.kinematics.forwardAssembly( ...
                q, testCase.Geometry, struct('mode', "ideal"));
            q.lower = q.lower + deg2rad([0.1, -0.1]);
            q.upper = q.lower;
            options = struct( ...
                'mode', "ideal", ...
                'branchMode', "continuous", ...
                'previousAssembly', previous, ...
                'maxContinuityCost', 5e-3);

            assembly = duallink5.kinematics.forwardAssembly( ...
                q, testCase.Geometry, options);

            testCase.verifyTrue(assembly.quality.valid);
            testCase.verifyEqual(assembly.lower.quality.branchId, ...
                previous.lower.quality.branchId);
            testCase.verifyEqual(assembly.upperLocal.quality.branchId, ...
                previous.upperLocal.quality.branchId);
        end

        function rejectsNonRigidPoseTransforms(testCase)
            pose = duallink5.kinematics.forwardFiveBar( ...
                testCase.Q, testCase.Geometry);
            invalidRotations = { ...
                2 * eye(2), ...
                [1, 0.1; 0, 1], ...
                zeros(2), ...
                diag([1, -1]), ...
                [1, 0; 0, 1i], ...
                [1, NaN; 0, 1]};
            invalidTranslations = { ...
                [0; NaN], [0; 1i], ["0"; "1"], [0; 0; 0]};

            for index = 1:numel(invalidRotations)
                testCase.verifyError( ...
                    @() duallink5.kinematics.transformFiveBarPose( ...
                    pose, invalidRotations{index}, [0; 0]), ...
                    'duallink5:kinematics:InvalidTransform');
            end
            for index = 1:numel(invalidTranslations)
                testCase.verifyError( ...
                    @() duallink5.kinematics.transformFiveBarPose( ...
                    pose, eye(2), invalidTranslations{index}), ...
                    'duallink5:kinematics:InvalidTransform');
            end
        end

        function rigidPoseTransformPreservesGeometry(testCase)
            pose = duallink5.kinematics.forwardFiveBar( ...
                testCase.Q, testCase.Geometry);
            angle = 0.37;
            rotation = [cos(angle), -sin(angle); ...
                sin(angle), cos(angle)];
            translation = [0.12, -0.03];

            transformed = ...
                duallink5.kinematics.transformFiveBarPose( ...
                pose, rotation, translation);

            names = fieldnames(pose.points);
            for index = 1:numel(names)
                name = names{index};
                testCase.verifyEqual( ...
                    norm(transformed.points.(name) - ...
                    transformed.points.A), ...
                    norm(pose.points.(name) - pose.points.A), ...
                    'AbsTol', 1e-12);
            end
            expectedOrientation = atan2( ...
                sin(pose.sharedLink.orientation + angle), ...
                cos(pose.sharedLink.orientation + angle));
            testCase.verifyEqual( ...
                transformed.sharedLink.orientation, ...
                expectedOrientation, 'AbsTol', 1e-12);
            testCase.verifyEqual(transformed.metadata.rotation, rotation);
            testCase.verifyEqual( ...
                transformed.metadata.translation, translation.');
        end

        function idealTaskRejectsMalformedValidFlag(testCase)
            q.lower = testCase.Q;
            q.upper = testCase.Q;
            assembly = duallink5.kinematics.forwardAssembly( ...
                q, testCase.Geometry);
            malformed = {NaN, 2, -1, [true, false], "true"};

            for index = 1:numel(malformed)
                candidate = assembly;
                candidate.quality.valid = malformed{index};
                testCase.verifyError( ...
                    @() duallink5.kinematics.taskPose( ...
                    candidate, struct('kind', "sharedCenter")), ...
                    'duallink5:kinematics:InvalidAssemblyPose');
            end

            assembly.quality.valid = uint8(1);
            task = duallink5.kinematics.taskPose( ...
                assembly, struct('kind', "sharedCenter"));
            testCase.verifyEqual( ...
                task.position, assembly.sharedLink.center);
        end

        function diagnosticTaskRejectsMalformedAvailabilityFlag(testCase)
            q.lower = testCase.Q;
            q.upper = testCase.Q + deg2rad([0.2, -0.1]);
            assembly = duallink5.kinematics.forwardAssembly( ...
                q, testCase.Geometry, struct('mode', "diagnostic"));
            taskSpec = struct('kind', "sharedCenter", 'side', "lower");
            malformed = {NaN, 2, -1, [true, false], "true"};

            for index = 1:numel(malformed)
                candidate = assembly;
                candidate.quality.diagnosticAvailable = ...
                    malformed{index};
                testCase.verifyError( ...
                    @() duallink5.kinematics.taskPose( ...
                    candidate, taskSpec), ...
                    'duallink5:kinematics:InvalidAssemblyPose');
            end

            assembly.quality.diagnosticAvailable = uint8(1);
            task = duallink5.kinematics.taskPose(assembly, taskSpec);
            testCase.verifyEqual(task.position, ...
                assembly.sharedLinkEstimates.lower.center);
        end

        function integerOffsetMatchesDoubleOffset(testCase)
            assembly = testCase.idealAssembly();
            integerTask = duallink5.kinematics.taskPose(assembly, ...
                struct('kind', "marker", ...
                'offset', int16([1; -2]), ...
                'includeOrientation', true));
            doubleTask = duallink5.kinematics.taskPose(assembly, ...
                struct('kind', "marker", ...
                'offset', double([1; -2]), ...
                'includeOrientation', true));

            testCase.verifyClass(integerTask.position, 'double');
            testCase.verifyEqual( ...
                integerTask.vector, doubleTask.vector, 'AbsTol', 1e-12);
        end

        function integerOrientationOffsetMatchesDoubleOffset(testCase)
            assembly = testCase.idealAssembly();
            integerTask = duallink5.kinematics.taskPose(assembly, ...
                struct('kind', "sharedCenter", ...
                'orientationOffset', int16(1), ...
                'includeOrientation', true));
            doubleTask = duallink5.kinematics.taskPose(assembly, ...
                struct('kind', "sharedCenter", ...
                'orientationOffset', 1, ...
                'includeOrientation', true));

            testCase.verifyClass(integerTask.orientation, 'double');
            testCase.verifyEqual(integerTask.vector, ...
                doubleTask.vector, 'AbsTol', 1e-12);
        end

        function complexTaskExtrinsicsThrow(testCase)
            assembly = testCase.idealAssembly();

            testCase.verifyError( ...
                @() duallink5.kinematics.taskPose(assembly, ...
                struct('kind', "marker", 'offset', [1 + 1i; 0])), ...
                'duallink5:kinematics:InvalidTaskSpec');
            testCase.verifyError( ...
                @() duallink5.kinematics.taskPose(assembly, ...
                struct('kind', "sharedCenter", ...
                'orientationOffset', 1 + 1i)), ...
                'duallink5:kinematics:InvalidTaskSpec');
        end
    end

    methods (Access = private)
        function assembly = idealAssembly(testCase)
            q.lower = testCase.Q;
            q.upper = testCase.Q;
            assembly = duallink5.kinematics.forwardAssembly( ...
                q, testCase.Geometry);
        end
    end
end
