classdef TestInverseKinematics < matlab.unittest.TestCase
    properties
        Geometry
        Q
    end

    methods (TestMethodSetup)
        function setup(testCase)
            testDir = fileparts(mfilename('fullpath'));
            projectRoot = fileparts(fileparts(testDir));
            run(fullfile(projectRoot, 'startup.m'));
            testCase.Geometry = duallink5.model.defaultGeometry();
            testCase.Q = deg2rad([85, 52.93]);
        end
    end

    methods (Test)
        function sharedCenterRoundTripsAllValidatedSolutions(testCase)
            g = testCase.Geometry;
            options = struct('collisionProfile', "centerline");
            sourcePose = duallink5.kinematics.forwardFiveBar( ...
                testCase.Q, g, options);
            target = struct( ...
                'kind', "sharedCenter", ...
                'position', sourcePose.sharedLink.center);

            solutions = duallink5.kinematics.inverseKinematics( ...
                target, g, options);

            testCase.verifyNumElements(solutions, 2);
            q = vertcat(solutions.q);
            [~, order] = sort(q(:, 2));
            solutions = solutions(order);
            q = vertcat(solutions.q);
            testCase.verifyEqual( ...
                [solutions.branchId], int8([-1, -1]));
            testCase.verifyEqual(rad2deg(q(:, 2)).', ...
                [52.93, 129.922883026159], 'AbsTol', 1e-9);
            wrappedDifference = atan2( ...
                sin(q - testCase.Q), cos(q - testCase.Q));
            testCase.verifyLessThan( ...
                min(vecnorm(wrappedDifference, 2, 2)), 1e-7);
            testCase.verifyTrue(all([solutions.valid]));
            testCase.verifyTrue(all([solutions.collisionFree]));
            testCase.verifyLessThan( ...
                max([solutions.closureResidual]), 1e-9);

            for index = 1:numel(solutions)
                forwardOptions = options;
                forwardOptions.branchMode = "fixed";
                forwardOptions.branchId = solutions(index).branchId;
                pose = duallink5.kinematics.forwardFiveBar( ...
                    solutions(index).q, g, forwardOptions);
                testCase.verifyEqual(pose.sharedLink.center, ...
                    target.position, 'AbsTol', 1e-8);
            end
            testCase.verifyLessThan( ...
                max([solutions.forwardResidual]), 1e-8);
        end

        function pointGRoundTripFindsValidatedSolution(testCase)
            g = testCase.Geometry;
            sourcePose = duallink5.kinematics.forwardFiveBar( ...
                testCase.Q, g);
            target = struct( ...
                'kind', "pointG", ...
                'position', sourcePose.points.G);

            solutions = duallink5.kinematics.inverseKinematics( ...
                target, g, struct());

            testCase.verifyNotEmpty(solutions);
            testCase.verifyLessThan( ...
                min([solutions.forwardResidual]), 1e-8);
        end

        function unreachableSharedCenterReturnsEmpty(testCase)
            target = struct( ...
                'kind', "sharedCenter", ...
                'position', [1; 1]);

            solutions = duallink5.kinematics.inverseKinematics( ...
                target, testCase.Geometry, struct());

            testCase.verifyEmpty(solutions);
        end

        function looseForwardTolerancePreservesDistinctSolutions(testCase)
            g = testCase.Geometry;
            options = struct( ...
                'collisionProfile', "centerline", ...
                'forwardTolerance', 2);
            sourcePose = duallink5.kinematics.forwardFiveBar( ...
                testCase.Q, g, struct('collisionProfile', "centerline"));
            target = struct( ...
                'kind', "sharedCenter", ...
                'position', sourcePose.sharedLink.center);

            solutions = duallink5.kinematics.inverseKinematics( ...
                target, g, options);

            testCase.verifyNumElements(solutions, 2);
            q = vertcat(solutions.q);
            testCase.verifyEqual(sort(rad2deg(q(:, 2))).', ...
                [52.93, 129.922883026159], 'AbsTol', 1e-9);
            testCase.verifyTrue(all([solutions.valid]));
            testCase.verifyTrue(all([solutions.collisionFree]));
            for index = 1:numel(solutions)
                testCase.verifyTrue(solutions(index).pose.quality.valid);
                testCase.verifyTrue( ...
                    solutions(index).pose.quality.collisionFree);
            end
        end

        function invalidJointToleranceIsRejected(testCase)
            target = struct( ...
                'kind', "sharedCenter", ...
                'position', [1; 1]);
            invalidValues = {0, -1, NaN, Inf, [1e-10, 1e-10], 1 + 1i};

            for index = 1:numel(invalidValues)
                options = struct('jointTolerance', invalidValues{index});
                testCase.verifyError( ...
                    @() duallink5.kinematics.inverseKinematics( ...
                        target, testCase.Geometry, options), ...
                    'duallink5:kinematics:InvalidIKOptions');
            end
        end

        function invalidCollisionProfileIsTargetIndependent(testCase)
            sourcePose = duallink5.kinematics.forwardFiveBar( ...
                testCase.Q, testCase.Geometry);
            targets = { ...
                struct('kind', "sharedCenter", ...
                    'position', sourcePose.sharedLink.center), ...
                struct('kind', "sharedCenter", 'position', [1; 1])};
            options = struct('collisionProfile', "invalid");

            for index = 1:numel(targets)
                testCase.verifyError( ...
                    @() duallink5.kinematics.inverseKinematics( ...
                        targets{index}, testCase.Geometry, options), ...
                    'duallink5:validation:InvalidCollisionProfile');
            end
        end

        function physicalConfigurationIsValidatedBeforeReachability(testCase)
            target = struct( ...
                'kind', "sharedCenter", ...
                'position', [1; 1]);
            options = struct('collisionProfile', "physicalClearance");

            testCase.verifyError( ...
                @() duallink5.kinematics.inverseKinematics( ...
                    target, testCase.Geometry, options), ...
                'duallink5:validation:MissingClearanceGeometry');
        end

        function unknownIKOptionsAreRejected(testCase)
            target = struct( ...
                'kind', "sharedCenter", ...
                'position', [1; 1]);

            testCase.verifyError( ...
                @() duallink5.kinematics.inverseKinematics( ...
                    target, testCase.Geometry, ...
                    struct('arbitraryOption', true)), ...
                'duallink5:kinematics:InvalidIKOptions');
        end

        function malformedOptionContainersUseIKError(testCase)
            target = struct( ...
                'kind', "sharedCenter", ...
                'position', [1; 1]);
            malformed = {[], 42, "centerline", repmat(struct(), 1, 2)};

            for index = 1:numel(malformed)
                testCase.verifyError( ...
                    @() duallink5.kinematics.inverseKinematics( ...
                        target, testCase.Geometry, malformed{index}), ...
                    'duallink5:kinematics:InvalidIKOptions');
            end
        end

        function malformedTargetsUseIKErrorIdentifiers(testCase)
            valid = struct( ...
                'kind', "sharedCenter", ...
                'position', [0; 0]);
            malformed = { ...
                42, ...
                struct(), ...
                repmat(valid, 1, 2), ...
                rmfield(valid, 'kind'), ...
                struct('kind', ["sharedCenter", "pointG"], ...
                    'position', [0; 0]), ...
                struct('kind', "sharedCenter", 'position', [0; NaN]), ...
                struct('kind', "sharedCenter", 'position', [0; 1i]), ...
                struct('kind', "sharedCenter", 'position', [0; 0; 0]), ...
                struct('kind', "sharedCenter", 'position', [true; false])};

            for index = 1:numel(malformed)
                testCase.verifyError( ...
                    @() duallink5.kinematics.inverseKinematics( ...
                        malformed{index}, testCase.Geometry, struct()), ...
                    'duallink5:kinematics:InvalidIKTarget');
            end

            unsupported = struct( ...
                'kind', "sharedOffset", ...
                'position', [0; 0]);
            testCase.verifyError( ...
                @() duallink5.kinematics.inverseKinematics( ...
                    unsupported, testCase.Geometry, struct()), ...
                'duallink5:kinematics:UnsupportedIKTask');
        end
    end
end
