classdef TestAssembly < matlab.unittest.TestCase
    properties
        Geometry
        Q
    end

    methods (TestMethodSetup)
        function setup(testCase)
            testDir = fileparts(mfilename('fullpath'));
            projectRoot = fileparts(fileparts(testDir));
            run(fullfile(projectRoot, 'startup.m'));
            testCase.Geometry = duallink5.model.defaultGeometry();
            testCase.Q = deg2rad([85, 52.93]);
        end
    end

    methods (Test)
        function idealSymmetryClosesSharedLink(testCase)
            q.lower = testCase.Q;
            q.upper = testCase.Q;
            assembly = duallink5.kinematics.forwardAssembly( ...
                q, testCase.Geometry, struct('mode', "ideal"));

            testCase.verifyTrue(assembly.quality.valid);
            testCase.verifyLessThan(norm(assembly.symmetryResidual), 1e-10);
            testCase.verifyEqual(assembly.lower.points.E, ...
                assembly.upper.points.D, 'AbsTol', 1e-10);
            testCase.verifyEqual(assembly.lower.points.D, ...
                assembly.upper.points.E, 'AbsTol', 1e-10);
        end

        function diagnosticModeReportsPerturbation(testCase)
            q.lower = testCase.Q;
            q.upper = testCase.Q + deg2rad([0.2, -0.1]);
            assembly = duallink5.kinematics.forwardAssembly( ...
                q, testCase.Geometry, struct('mode', "diagnostic"));

            lowerEstimate = assembly.sharedLinkEstimates.lower;
            upperEstimate = assembly.sharedLinkEstimates.upper;
            expected = [upperEstimate.center - lowerEstimate.center; ...
                atan2(sin(upperEstimate.orientation - ...
                lowerEstimate.orientation), ...
                cos(upperEstimate.orientation - ...
                lowerEstimate.orientation))];
            testCase.verifyEqual(assembly.symmetryResidual, expected, ...
                'AbsTol', 1e-12);
            testCase.verifyEqual(assembly.symmetryResidual, ...
                [2.88896613817112e-4; -5.48531152552295e-5; ...
                8.19584059540190e-4], 'AbsTol', 1e-12);
            testCase.verifyGreaterThan(assembly.symmetryResidual(1), 0);
            testCase.verifyLessThan(assembly.symmetryResidual(2), 0);
            testCase.verifyGreaterThan(assembly.symmetryResidual(3), 0);
            testCase.verifyEqual( ...
                assembly.metadata.symmetryResidualUnits, ...
                ["m"; "m"; "rad"]);
            testCase.verifyEqual( ...
                assembly.quality.statusCode, "SHARED_LINK_MISMATCH");
            testCase.verifyFalse(assembly.quality.valid);
            testCase.verifyTrue(assembly.quality.diagnosticAvailable);
            testCase.verifyFalse(isfield(assembly, 'sharedLink'));
            testCase.verifyError( ...
                @() duallink5.kinematics.taskPose( ...
                assembly, struct('kind', "sharedCenter")), ...
                'duallink5:kinematics:AmbiguousDiagnosticTask');
        end

        function taskSpecSelectsCenterAndOffset(testCase)
            q.lower = testCase.Q;
            q.upper = testCase.Q;
            assembly = duallink5.kinematics.forwardAssembly( ...
                q, testCase.Geometry);

            center = duallink5.kinematics.taskPose(assembly, ...
                struct('kind', "sharedCenter", ...
                'includeOrientation', true));
            offset = duallink5.kinematics.taskPose(assembly, ...
                struct('kind', "sharedOffset", 'offset', [10e-3; 0], ...
                'includeOrientation', true));
            marker = duallink5.kinematics.taskPose(assembly, ...
                struct('kind', "marker", 'offset', [10e-3; 0], ...
                'orientationOffset', 0.2, ...
                'includeOrientation', true));

            testCase.verifyEqual(center.position, ...
                assembly.sharedLink.center, 'AbsTol', 1e-12);
            testCase.verifyEqual( ...
                norm(offset.position - center.position), 10e-3, ...
                'AbsTol', 1e-12);
            testCase.verifyEqual( ...
                marker.position, offset.position, 'AbsTol', 1e-12);
            testCase.verifyEqual( ...
                atan2(sin(marker.orientation - center.orientation), ...
                cos(marker.orientation - center.orientation)), ...
                0.2, 'AbsTol', 1e-12);
        end

        function previousAssemblyControlsBothContinuousBranches(testCase)
            q.lower = testCase.Q;
            q.upper = testCase.Q;
            previous = duallink5.kinematics.forwardAssembly( ...
                q, testCase.Geometry, struct('mode', "ideal"));
            q.lower = q.lower + deg2rad([0.1, -0.1]);
            q.upper = q.lower;
            options = struct( ...
                'mode', "ideal", ...
                'branchMode', "continuous", ...
                'previousAssembly', previous, ...
                'maxContinuityCost', 5e-3);

            assembly = duallink5.kinematics.forwardAssembly( ...
                q, testCase.Geometry, options);

            testCase.verifyTrue(assembly.quality.valid);
            testCase.verifyEqual(assembly.lower.quality.branchId, ...
                previous.lower.quality.branchId);
            testCase.verifyEqual(assembly.upperLocal.quality.branchId, ...
                previous.upperLocal.quality.branchId);
        end
    end
end
