classdef TestSingularitySpace < matlab.unittest.TestCase
    properties
        Geometry
    end

    methods (TestMethodSetup)
        function setup(testCase)
            testDir = fileparts(mfilename('fullpath'));
            projectRoot = fileparts(fileparts(testDir));
            run(fullfile(projectRoot, 'startup.m'));
            testCase.Geometry = duallink5.model.defaultGeometry();
        end
    end

    methods (Test)
        function sampleFieldsHaveDocumentedShapes(testCase)
            grid.theta = deg2rad([84, 85, 86]);
            grid.phi = deg2rad([29, 30, 31, 32]);
            samples = duallink5.singularity.sampleSpace( ...
                grid, testCase.Geometry, struct());

            testCase.verifySize(samples.thetaGrid, [3, 4]);
            testCase.verifySize(samples.x, [3, 4]);
            testCase.verifySize(samples.constraintMatrix, [2, 2, 3, 4]);
            testCase.verifySize(samples.taskActuationMatrix, [2, 2, 3, 4]);
            testCase.verifySize(samples.taskJacobian, [2, 2, 3, 4]);
            testCase.verifySize( ...
                samples.singularValues.constraint, [2, 3, 4]);
            testCase.verifySize(samples.singularValues.task, [2, 3, 4]);
            testCase.verifyTrue(all( ...
                samples.safeUsableMask <= ...
                samples.mechanicallyValidMask, 'all'));
            testCase.verifyTrue(all( ...
                samples.mechanicallyValidMask <= ...
                samples.theoreticalReachableMask, 'all'));
        end

        function singlePointGridPreservesMetadataAndHasEmptyCurves(testCase)
            grid.theta = deg2rad(85);
            grid.phi = deg2rad(30);
            options = struct('branchId', int8(-1), ...
                'exactThreshold', 2e-8, ...
                'nearMetricThreshold', 0.08, ...
                'nearConditionThreshold', 250, ...
                'collisionProfile', "none", ...
                'topologyProfile', "none");
            samples = duallink5.singularity.sampleSpace( ...
                grid, testCase.Geometry, options);

            testCase.verifySize(samples.thetaGrid, [1, 1]);
            curveNames = {'typeITheta', 'typeIPhi', ...
                'typeIIOuter', 'typeIIInner', 'typeIII'};
            for index = 1:numel(curveNames)
                testCase.verifyEmpty(samples.curves.(curveNames{index}));
            end
            testCase.verifyEqual(samples.metadata.units, ...
                testCase.Geometry.units);
            testCase.verifyEqual(samples.metadata.branchId, int8(-1));
            testCase.verifyEqual(samples.metadata.exactThreshold, 2e-8);
            testCase.verifyEqual(samples.metadata.nearMetricThreshold, 0.08);
            testCase.verifyEqual( ...
                samples.metadata.nearConditionThreshold, 250);
            testCase.verifyEqual(samples.metadata.collisionProfile, "none");
            testCase.verifyEqual(samples.metadata.topologyProfile, "none");
        end

        function exactTangencyKeepsFiniteTaskPoint(testCase)
            grid.theta = [0.83109759906031577, deg2rad(85)];
            grid.phi = [deg2rad(30), deg2rad(56.5)];
            samples = duallink5.singularity.sampleSpace( ...
                grid, testCase.Geometry, ...
                struct('collisionProfile', "none", ...
                'topologyProfile', "none"));
            row = 1;
            column = 2;

            testCase.verifyTrue( ...
                samples.theoreticalReachableMask(row, column));
            testCase.verifyTrue(samples.exact.typeII(row, column));
            testCase.verifyTrue(isfinite(samples.x(row, column)));
            testCase.verifyTrue(isfinite(samples.y(row, column)));
            testCase.verifyTrue(all(isnan( ...
                samples.taskJacobian(:, :, row, column)), 'all'));
            testCase.verifyFalse( ...
                samples.mechanicallyValidMask(row, column));
        end

        function topologyProfileChangesOnlyTopologyRejection(testCase)
            grid.theta = deg2rad([13.5, 14.5]);
            grid.phi = deg2rad([83, 84]);
            reference = duallink5.singularity.sampleSpace( ...
                grid, testCase.Geometry, ...
                struct('topologyProfile', "reference"));
            unfiltered = duallink5.singularity.sampleSpace( ...
                grid, testCase.Geometry, ...
                struct('topologyProfile', "none"));

            target = reference.thetaGrid == deg2rad(13.5) & ...
                reference.phiGrid == deg2rad(84);
            testCase.verifyEqual(reference.reasonMap(target), ...
                "ASSEMBLY_TOPOLOGY_MISMATCH");
            testCase.verifyFalse(reference.mechanicallyValidMask(target));
            testCase.verifyTrue(unfiltered.mechanicallyValidMask(target));
            testCase.verifyEqual( ...
                reference.theoreticalReachableMask, ...
                unfiltered.theoreticalReachableMask);
        end

        function collisionProfileChangesOnlyCollisionRejection(testCase)
            grid.theta = deg2rad([179, 180]);
            grid.phi = deg2rad([68.25, 69]);
            collision = duallink5.singularity.sampleSpace( ...
                grid, testCase.Geometry, ...
                struct('collisionProfile', "centerline", ...
                'topologyProfile', "none"));
            unfiltered = duallink5.singularity.sampleSpace( ...
                grid, testCase.Geometry, ...
                struct('collisionProfile', "none", ...
                'topologyProfile', "none"));

            target = collision.thetaGrid == deg2rad(180) & ...
                collision.phiGrid == deg2rad(68.25);
            testCase.verifyTrue(collision.theoreticalReachableMask(target));
            testCase.verifyEqual(collision.reasonMap(target), ...
                "PARALLEL_SHARED_COLLISION");
            testCase.verifyFalse(collision.mechanicallyValidMask(target));
            testCase.verifyTrue(unfiltered.mechanicallyValidMask(target));
            testCase.verifyEqual(collision.theoreticalReachableMask, ...
                unfiltered.theoreticalReachableMask);
        end

        function exactTypeIIIGridPointCreatesMappedLocus(testCase)
            geometry = testCase.Geometry;
            geometry.links.link3 = 30e-3;
            geometry.links.link4 = 32e-3;
            geometry = duallink5.model.validateGeometry(geometry);
            grid.theta = 0;
            grid.phi = 0;
            samples = duallink5.singularity.sampleSpace( ...
                grid, geometry, struct('collisionProfile', "none", ...
                'topologyProfile', "none"));

            testCase.verifyTrue(samples.exact.typeIII);
            testCase.verifyNumElements(samples.curves.typeIII, 1);
            testCase.verifyEqual(samples.curves.typeIII.theta, 0);
            testCase.verifyEqual(samples.curves.typeIII.phi, 0);
            testCase.verifyTrue(all(isfinite( ...
                samples.curves.typeIII.pointG), 'all'));
        end

        function nonGridTypeIIIIsRootRefinedFromTypeIICurve(testCase)
            grid.theta = deg2rad(47:1:50);
            grid.phi = deg2rad(55:1:58);
            options = struct('collisionProfile', "none", ...
                'topologyProfile', "none");
            samples = duallink5.singularity.sampleSpace( ...
                grid, testCase.Geometry, options);

            testCase.verifyFalse(any(samples.exact.typeIII, 'all'));
            testCase.verifyNotEmpty(samples.curves.typeIII);
            expected = [0.846282132507182; 0.985169611228796];
            locations = [[samples.curves.typeIII.theta]; ...
                [samples.curves.typeIII.phi]];
            [distance, closest] = min(vecnorm(locations - expected, 2, 1));
            testCase.verifyLessThan(distance, 1e-7);
            q = locations(:, closest).';
            result = duallink5.singularity.evaluate( ...
                q, testCase.Geometry, options);
            testCase.verifyTrue(result.logical.exact.typeIII);
            testCase.verifyEqual(result.logical.closureStatusCode, ...
                "NEAR_SINGULAR");
            tolerance = 32 * eps(max([ ...
                testCase.Geometry.links.link3, ...
                testCase.Geometry.links.link4]));
            testCase.verifyLessThanOrEqual( ...
                abs(result.logical.closureDistance - ...
                abs(testCase.Geometry.links.link4 - ...
                testCase.Geometry.links.link3)), tolerance);
        end

        function coarseTypeIICurvesSeedTypeIIIWithoutSignChange(testCase)
            grid.theta = deg2rad([38, 45, 52]);
            grid.phi = deg2rad([50, 60, 75, 90]);
            options = struct('collisionProfile', "none", ...
                'topologyProfile', "none");
            samples = duallink5.singularity.sampleSpace( ...
                grid, testCase.Geometry, options);

            testCase.verifyFalse(any(samples.exact.typeIII, 'all'));
            testCase.verifyNumElements(samples.curves.typeIIInner, 2);
            for curveIndex = 1:numel(samples.curves.typeIIInner)
                curve = samples.curves.typeIIInner(curveIndex);
                thetaMetric = zeros(1, numel(curve.theta));
                phiMetric = zeros(1, numel(curve.theta));
                for pointIndex = 1:numel(curve.theta)
                    result = duallink5.singularity.evaluate( ...
                        [curve.theta(pointIndex), ...
                        curve.phi(pointIndex)], ...
                        testCase.Geometry, options);
                    thetaMetric(pointIndex) = ...
                        result.logical.signedIndicator.typeITheta;
                    phiMetric(pointIndex) = ...
                        result.logical.signedIndicator.typeIPhi;
                end
                testCase.verifyGreaterThan( ...
                    min(abs(thetaMetric)), 1e-8);
                testCase.verifyGreaterThan( ...
                    min(abs(phiMetric)), 1e-8);
                testCase.verifyTrue(all(thetaMetric > 0) || ...
                    all(thetaMetric < 0));
                testCase.verifyTrue(all(phiMetric > 0) || ...
                    all(phiMetric < 0));
            end

            testCase.assertNotEmpty(samples.curves.typeIII);
            expected = [ ...
                0.731311068250780, 0.846282132507208; ...
                1.371598519684484, 0.985169611228810];
            locations = [[samples.curves.typeIII.theta]; ...
                [samples.curves.typeIII.phi]];
            for expectedIndex = 1:size(expected, 2)
                [distance, closest] = min(vecnorm( ...
                    locations - expected(:, expectedIndex), 2, 1));
                testCase.verifyLessThan(distance, 1e-7);
                result = duallink5.singularity.evaluate( ...
                    locations(:, closest).', ...
                    testCase.Geometry, options);
                testCase.verifyTrue(result.logical.exact.typeIII);
            end
        end

        function tinyThresholdReturnsOnlyPublicExactCurves(testCase)
            options = struct('collisionProfile', "none", ...
                'topologyProfile', "none", ...
                'exactThreshold', 1e-20);
            grids = { ...
                struct('theta', deg2rad(44:0.25:46.5), ...
                'phi', deg2rad(78:0.25:80)), ...
                struct('theta', deg2rad(56:0.25:58), ...
                'phi', deg2rad(0:0.25:2))};
            names = {'typeITheta', 'typeIPhi'};
            for caseIndex = 1:2
                lastwarn('');
                samples = duallink5.singularity.sampleSpace( ...
                    grids{caseIndex}, testCase.Geometry, options);
                [warningMessage, ~] = lastwarn;
                testCase.verifyEmpty(warningMessage);
                curves = samples.curves.(names{caseIndex});
                allPublicExact = true;
                for curveIndex = 1:numel(curves)
                    curve = curves(curveIndex);
                    for pointIndex = 1:numel(curve.theta)
                        result = duallink5.singularity.evaluate( ...
                            [curve.theta(pointIndex), ...
                            curve.phi(pointIndex)], ...
                            testCase.Geometry, options);
                        allPublicExact = allPublicExact && ...
                            result.logical.exact.(names{caseIndex});
                    end
                end
                testCase.verifyTrue(allPublicExact);
            end

            typeIIIGrid.theta = deg2rad(47:1:50);
            typeIIIGrid.phi = deg2rad(55:1:58);
            lastwarn('');
            samples = duallink5.singularity.sampleSpace( ...
                typeIIIGrid, testCase.Geometry, options);
            [warningMessage, ~] = lastwarn;
            testCase.verifyEmpty(warningMessage);
            allPublicExact = true;
            for curveIndex = 1:numel(samples.curves.typeIII)
                curve = samples.curves.typeIII(curveIndex);
                for pointIndex = 1:numel(curve.theta)
                    result = duallink5.singularity.evaluate( ...
                        [curve.theta(pointIndex), ...
                        curve.phi(pointIndex)], ...
                        testCase.Geometry, options);
                    allPublicExact = allPublicExact && ...
                        result.logical.exact.typeIII;
                end
            end
            testCase.verifyTrue(allPublicExact);
        end

        function samplerExtractsBothTypeISubtypeCurves(testCase)
            grids = { ...
                struct('theta', deg2rad(44:0.25:46.5), ...
                'phi', deg2rad(78:0.25:80)), ...
                struct('theta', deg2rad(56:0.25:58), ...
                'phi', deg2rad(0:0.25:2))};
            names = {'typeITheta', 'typeIPhi'};
            options = struct('collisionProfile', "none", ...
                'topologyProfile', "none");
            for caseIndex = 1:2
                samples = duallink5.singularity.sampleSpace( ...
                    grids{caseIndex}, testCase.Geometry, options);
                curves = samples.curves.(names{caseIndex});
                testCase.verifyNotEmpty(curves);
                for curveIndex = 1:numel(curves)
                    curve = curves(curveIndex);
                    testCase.verifyTrue( ...
                        islogical(curve.adjacentMechanical));
                    testCase.verifySize(curve.pointG, ...
                        [2, numel(curve.theta)]);
                    testCase.verifySize(curve.adjacentMechanical, ...
                        [1, numel(curve.theta)]);
                    for pointIndex = 1:numel(curve.theta)
                        result = duallink5.singularity.evaluate( ...
                            [curve.theta(pointIndex), ...
                            curve.phi(pointIndex)], ...
                            testCase.Geometry, options);
                        testCase.verifyLessThan(abs( ...
                            result.logical.signedIndicator.( ...
                            names{caseIndex})), 1e-4);
                    end
                end
            end
        end

        function denseGridExtractsOuterTypeIICurve(testCase)
            grid.theta = deg2rad(170:0.5:180);
            grid.phi = deg2rad(60:0.5:80);
            samples = duallink5.singularity.sampleSpace( ...
                grid, testCase.Geometry, ...
                struct('collisionProfile', "none", ...
                'topologyProfile', "none"));

            pointCount = sum(arrayfun( ...
                @(curve)numel(curve.theta), ...
                samples.curves.typeIIOuter));
            testCase.verifyGreaterThan(pointCount, 2);
            finiteCurves = arrayfun(@(curve) ...
                all(isfinite(curve.pointG), 'all'), ...
                samples.curves.typeIIOuter);
            testCase.verifyTrue(all(finiteCurves));
            theta = [samples.curves.typeIIOuter.theta];
            phi = [samples.curves.typeIIOuter.phi];
            L = testCase.Geometry.links;
            deltaX = L.link1 * cos(theta) - L.link5 + ...
                L.link2 * cos(phi);
            deltaY = L.link1 * sin(theta) - L.link2 * sin(phi);
            outerTarget = L.link3 + L.link4;
            residual = hypot(deltaX, deltaY) - outerTarget;
            tolerance = 32 * eps(max( ...
                [outerTarget, L.link3, L.link4]));
            testCase.verifyLessThanOrEqual( ...
                max(abs(residual)), tolerance);
        end

        function rejectsMalformedGrid(testCase)
            malformed = { ...
                struct('theta', [0, 1]), ...
                struct('theta', [0, 1], 'phi', [0, NaN]), ...
                struct('theta', [1, 0], 'phi', [0, 1]), ...
                struct('theta', [0, 0], 'phi', [0, 1])};
            for index = 1:numel(malformed)
                testCase.verifyError( ...
                    @()duallink5.singularity.sampleSpace( ...
                    malformed{index}, testCase.Geometry, struct()), ...
                    'duallink5:singularity:InvalidGrid');
            end
        end
    end
end
