function result = evaluateCouplingPrepared(qLower, context)
%EVALUATECOUPLINGPREPARED Evaluate using a validated immutable context.
geometry = context.geometry;
options = context.options;
reference = context.reference;

kinematics = duallink5.kinematics.forwardPassiveDoublet( ...
    qLower, geometry, struct( ...
    'collisionProfile', "none", ...
    'lowerBranchMode', options.lowerBranchMode, ...
    'lowerBranchId', options.lowerBranchId));
if kinematics.quality.closureStatusCode == "NEAR_SINGULAR"
    kinematics = recoverLowerTangency(qLower, geometry, options);
end
assessment = assessCouplingAssembly( ...
    qLower, kinematics, geometry, options, reference);

result = initializeResult( ...
    kinematics, assessment, qLower, geometry, options, reference);
if ~assessment.theoreticallyReachable || ~hasCouplingGeometry(kinematics)
    result.statusCode = string(kinematics.quality.closureStatusCode);
    return
end

[coupling, lowerClosureSingular] = couplingMetrics( ...
    kinematics, qLower, geometry, options);
result.coupling = coupling;
result.exactCouplingSingular = ...
    coupling.margin <= options.exactThreshold;
if result.exactCouplingSingular
    result.coupling.taskJacobian = NaN(2);
end
result.nearCouplingSingular = result.exactCouplingSingular || ...
    coupling.margin < options.nearMetricThreshold || ...
    result.coupling.conditionNumber > options.nearConditionThreshold;
result.engineeringWarning = ...
    abs(qLower(2)) <= geometry.analysis.couplingWarningAngle;
result.statusCode = classify(result, lowerClosureSingular);
end

function result = initializeResult( ...
        kinematics, assessment, q, geometry, options, reference)
result = struct();
result.kinematics = kinematics;
result.coupling = invalidCoupling();
result.exactCouplingSingular = false;
result.nearCouplingSingular = false;
result.engineeringWarning = ...
    abs(q(2)) <= geometry.analysis.couplingWarningAngle;
result.theoreticallyReachable = assessment.theoreticallyReachable;
result.mechanicallyValid = assessment.mechanicallyValid;
result.statusCode = string(assessment.statusCode);
result.assemblyStatusCode = string(assessment.statusCode);
result.metadata = struct( ...
    'qLower', q, ...
    'geometryVersion', string(geometry.version), ...
    'collisionProfile', options.collisionProfile, ...
    'topologyProfile', options.topologyProfile, ...
    'lowerBranchMode', options.lowerBranchMode, ...
    'lowerBranchId', options.lowerBranchId, ...
    'exactThreshold', options.exactThreshold, ...
    'nearMetricThreshold', options.nearMetricThreshold, ...
    'nearConditionThreshold', options.nearConditionThreshold, ...
    'couplingWarningAngle', geometry.analysis.couplingWarningAngle, ...
    'couplingReference', reference, ...
    'assemblyAssessment', assessment);
end

function coupling = invalidCoupling()
coupling = struct( ...
    'constraintMatrix', NaN(2), ...
    'actuationMatrix', NaN(2), ...
    'taskJacobian', NaN(2), ...
    'margin', NaN, ...
    'singularValues', NaN(2, 1), ...
    'sigmaMin', NaN, ...
    'conditionNumber', NaN, ...
    'passiveDirection', NaN(2, 1));
end

function valid = hasCouplingGeometry(kinematics)
valid = isfield(kinematics, 'upper') && ...
    isfield(kinematics.upper, 'points') && ...
    all(isfield(kinematics.upper.points, {'A', 'C'})) && ...
    isfield(kinematics, 'points') && ...
    isfield(kinematics.points, 'G') && ...
    all(isfinite([kinematics.upper.points.A; ...
    kinematics.upper.points.C; kinematics.points.G]));
end

function [coupling, lowerClosureSingular] = couplingMetrics( ...
        kinematics, q, geometry, options)
p = kinematics.lower.points;
upper = kinematics.upper.points;
L = geometry.links;
uAG = (kinematics.points.G - upper.A) / L.link5;
uCG = (kinematics.points.G - upper.C) / L.link2;
constraintMatrix = [uAG.'; uCG.'];
[~, singularMatrix, V] = svd(constraintMatrix);
singularValues = diag(singularMatrix);
margin = abs(cross2(uAG, uCG));
sigmaMin = singularValues(end);
if sigmaMin == 0
    conditionNumber = Inf;
else
    conditionNumber = singularValues(1) / sigmaMin;
end

u = p.D - p.C;
v = p.D - p.E;
lowerConstraint = [u.'; v.'];
lowerMargin = abs(cross2(u, v)) / (L.link3 * L.link4);
lowerClosureSingular = ...
    kinematics.lower.quality.statusCode == "NEAR_SINGULAR" || ...
    lowerMargin <= 32 * eps(1);
actuationMatrix = NaN(2);
taskJacobian = NaN(2);
if ~lowerClosureSingular
    theta = q(1);
    phi = q(2);
    dE = [L.link1 * [-sin(theta); cos(theta)], zeros(2, 1)];
    dC = [zeros(2, 1), L.link2 * [sin(phi); cos(phi)]];
    dD = zeros(2);
    for column = 1:2
        dD(:, column) = lowerConstraint \ [ ...
            u.' * dC(:, column); v.' * dE(:, column)];
    end
    dAupper = dD + dE;
    dCupper = dD + dE - dC;
    actuationMatrix = [ ...
        uAG.' * dAupper; uCG.' * dCupper];
    if margin > options.exactThreshold
        taskJacobian = constraintMatrix \ actuationMatrix;
    end
end

coupling = struct( ...
    'constraintMatrix', constraintMatrix, ...
    'actuationMatrix', actuationMatrix, ...
    'taskJacobian', taskJacobian, ...
    'margin', margin, ...
    'singularValues', singularValues, ...
    'sigmaMin', sigmaMin, ...
    'conditionNumber', conditionNumber, ...
    'passiveDirection', V(:, end));
end

function status = classify(result, lowerClosureSingular)
if ~result.theoreticallyReachable
    status = string(result.kinematics.quality.closureStatusCode);
elseif lowerClosureSingular
    status = "LOWER_CLOSURE_SINGULAR";
elseif result.exactCouplingSingular
    status = "COUPLING_SINGULAR";
elseif ~result.mechanicallyValid
    status = result.assemblyStatusCode;
elseif result.nearCouplingSingular
    status = "NEAR_COUPLING_SINGULAR";
elseif result.engineeringWarning
    status = "ENGINEERING_WARNING";
else
    status = "OK";
end
end

function result = recoverLowerTangency(q, geometry, options)
L = geometry.links;
A = zeros(2, 1);
B = [L.link5; 0];
E = L.link1 * [cos(q(1)); sin(q(1))];
C = [L.link5 - L.link2 * cos(q(2)); L.link2 * sin(q(2))];
[lowerCandidates, lowerStatus] = duallink5.kinematics.solveClosure( ...
    C, E, L.link3, L.link4, geometry.tolerance.length);
if isempty(lowerCandidates)
    result = duallink5.kinematics.forwardPassiveDoublet( ...
        q, geometry, struct('collisionProfile', "none", ...
        'lowerBranchMode', options.lowerBranchMode, ...
        'lowerBranchId', options.lowerBranchId));
    return
end
D = lowerCandidates(1).D;
parallel = duallink5.kinematics.computeParallelPoints( ...
    A, C, D, E, geometry);
lowerPoints = struct('A', A, 'B', B, 'C', C, 'D', D, 'E', E, ...
    'G', D + E - B);
names = fieldnames(parallel);
for index = 1:numel(names)
    lowerPoints.(names{index}) = parallel.(names{index});
end
Aupper = D + E - A;
Cupper = E + D - C;
[upperCandidates, upperStatus] = duallink5.kinematics.solveClosure( ...
    Aupper, Cupper, L.link5, L.link2, geometry.tolerance.length);
if isempty(upperCandidates)
    result = recoveredInvalidResult( ...
        lowerPoints, q, geometry, lowerStatus, upperStatus);
    return
end
costs = arrayfun(@(candidate) ...
    norm(candidate.D - lowerPoints.G), upperCandidates);
[~, selected] = min(costs);
candidate = upperCandidates(selected);
G = candidate.D;
upperPoints = struct('A', Aupper, 'B', G, 'C', Cupper, ...
    'D', E, 'E', D, 'G', B);
result = recoveredResult(lowerPoints, upperPoints, G, q, geometry, ...
    lowerCandidates(1), candidate, lowerStatus, upperStatus);
end

function result = recoveredInvalidResult( ...
        lowerPoints, q, geometry, lowerStatus, upperStatus)
result = struct();
result.lower = makePose( ...
    lowerPoints, lowerStatus, int8(0), 0, geometry, q);
result.upper = struct('points', struct(), 'quality', struct( ...
    'valid', false, 'statusCode', string(upperStatus)));
result.points = struct('G', NaN(2, 1), ...
    'Aupper', NaN(2, 1), 'Cupper', NaN(2, 1));
result.quality = struct( ...
    'valid', false, 'theoreticallyReachable', false, ...
    'statusCode', string(upperStatus), ...
    'closureStatusCode', string(upperStatus), ...
    'passiveBranchId', NaN, 'passiveOrientationSign', NaN);
result.metadata = struct('qLower', q, ...
    'geometryVersion', string(geometry.version));
end

function result = recoveredResult( ...
        lowerPoints, upperPoints, G, q, geometry, lowerCandidate, ...
        upperCandidate, lowerStatus, upperStatus)
result = struct();
result.lower = makePose( ...
    lowerPoints, lowerStatus, lowerCandidate.branchId, ...
    lowerCandidate.closureResidual, geometry, q);
result.upper = makePose( ...
    upperPoints, upperStatus, upperCandidate.branchId, ...
    upperCandidate.closureResidual, geometry, []);
result.points = struct( ...
    'G', G, 'Aupper', upperPoints.A, 'Cupper', upperPoints.C);
result.sharedLink = result.lower.sharedLink;
result.passiveCandidates = struct( ...
    'G', G, ...
    'branchId', upperCandidate.branchId, ...
    'orientationSign', upperCandidate.branchId, ...
    'closureResidual', upperCandidate.closureResidual);
result.residuals = recoveredResiduals(result, geometry);
result.quality = struct( ...
    'valid', false, ...
    'theoreticallyReachable', true, ...
    'statusCode', "LOWER_CLOSURE_SINGULAR", ...
    'closureStatusCode', string(upperStatus), ...
    'passiveBranchId', upperCandidate.branchId, ...
    'passiveOrientationSign', upperCandidate.branchId, ...
    'closureResidual', upperCandidate.closureResidual, ...
    'continuityCost', 0, ...
    'parallelSharedClearance', NaN);
result.metadata = struct( ...
    'units', geometry.units, ...
    'convention', geometry.convention, ...
    'geometryVersion', string(geometry.version), ...
    'qLower', q);
end

function pose = makePose( ...
        points, status, branchId, closureResidual, geometry, q)
pose.points = points;
pose.sharedLink = struct( ...
    'start', points.E, ...
    'end', points.D, ...
    'center', (points.D + points.E) / 2, ...
    'orientation', atan2( ...
    points.D(2) - points.E(2), points.D(1) - points.E(1)));
pose.quality = struct( ...
    'valid', true, ...
    'branchId', branchId, ...
    'closureResidual', closureResidual, ...
    'continuityCost', 0, ...
    'collisionFree', NaN, ...
    'clearanceModelApplied', false, ...
    'statusCode', string(status));
pose.metadata = struct( ...
    'units', geometry.units, ...
    'convention', geometry.convention, ...
    'geometryVersion', string(geometry.version));
if ~isempty(q)
    pose.metadata.q = q;
end
end

function residuals = recoveredResiduals(result, geometry)
lower = result.lower.points;
upper = result.upper.points;
L = geometry.links;
residuals.upperLinks = struct( ...
    'link1', norm(upper.E - upper.A) - L.link1, ...
    'link2', norm(upper.C - upper.B) - L.link2, ...
    'link3', norm(upper.D - upper.C) - L.link3, ...
    'link4', norm(upper.D - upper.E) - L.link4, ...
    'link5', norm(upper.B - upper.A) - L.link5);
residuals.upper = residuals.upperLinks;
residuals.alpha = parallelogramResiduals( ...
    lower.Palpha1, lower.Palpha2, lower.Palpha3, lower.Palpha4, ...
    L.link4, geometry.parallel.lengths.Palpha1_Palpha4);
residuals.beta = parallelogramResiduals( ...
    lower.Pbeta1, lower.Pbeta2, lower.Pbeta3, lower.Pbeta4, ...
    L.link4, geometry.parallel.lengths.Pbeta2_Pbeta3);
residuals.rigidLines = struct( ...
    'alphaLower', max([ ...
    pointLineDistance(lower.Palpha1, lower.A, lower.E), ...
    pointLineDistance(lower.Palpha4, lower.A, lower.E)]), ...
    'alphaUpper', max([ ...
    pointLineDistance(lower.Palpha2, lower.D, upper.A), ...
    pointLineDistance(lower.Palpha3, lower.D, upper.A)]), ...
    'betaLower', max([ ...
    pointLineDistance(lower.Pbeta2, lower.C, lower.D), ...
    pointLineDistance(lower.Pbeta3, lower.C, lower.D)]), ...
    'betaUpper', max([ ...
    pointLineDistance(lower.Pbeta1, lower.E, upper.C), ...
    pointLineDistance(lower.Pbeta4, lower.E, upper.C)]));
residuals.shared = struct( ...
    'upperDLowerE', norm(upper.D - lower.E), ...
    'upperELowerD', norm(upper.E - lower.D), ...
    'upperGLowerB', norm(upper.G - lower.B), ...
    'selectedGUpperB', norm(result.points.G - upper.B));
residuals.idealSymmetry = struct( ...
    'A', norm(upper.A - (lower.G + lower.B)), ...
    'B', norm(upper.B - lower.G), ...
    'C', norm(upper.C - (lower.G + lower.B - lower.C)), ...
    'D', norm(upper.D - lower.E), ...
    'E', norm(upper.E - lower.D), ...
    'G', norm(upper.G - lower.B));
residuals.maximum = maximumResidual(residuals);
end

function residuals = parallelogramResiduals(p1, p2, p3, p4, width, span)
side12 = p2 - p1;
side23 = p3 - p2;
side34 = p4 - p3;
side41 = p1 - p4;
residuals = struct( ...
    'side12Length', norm(side12) - width, ...
    'side23Length', norm(side23) - span, ...
    'side34Length', norm(side34) - width, ...
    'side41Length', norm(side41) - span, ...
    'oppositeLength12_34', norm(side12) - norm(side34), ...
    'oppositeLength23_41', norm(side23) - norm(side41), ...
    'transmissionParallel', parallelResidual(side12, -side34), ...
    'rigidParallel', parallelResidual(side23, -side41));
residuals.oppositeParallel = max( ...
    residuals.transmissionParallel, residuals.rigidParallel);
end

function value = parallelResidual(first, second)
value = abs(cross2(first, second)) / (norm(first) * norm(second));
end

function distance = pointLineDistance(point, first, second)
direction = second - first;
distance = abs(cross2(direction, point - first)) / norm(direction);
end

function maximum = maximumResidual(residuals)
values = collectNumericScalars(residuals);
values = values(isfinite(values));
if isempty(values)
    maximum = NaN;
else
    maximum = max(abs(values));
end
end

function values = collectNumericScalars(value)
values = zeros(1, 0);
names = fieldnames(value);
for index = 1:numel(names)
    field = value.(names{index});
    if isstruct(field)
        values = [values, collectNumericScalars(field)]; %#ok<AGROW>
    elseif isnumeric(field) && isreal(field) && isscalar(field)
        values(end + 1) = double(field); %#ok<AGROW>
    end
end
end

function value = cross2(first, second)
value = first(1) * second(2) - first(2) * second(1);
end
