function options = normalizeCouplingOptions(input, geometry)
%NORMALIZECOUPLINGOPTIONS Validate single-configuration coupling options.
if ~isstruct(input) || ~isscalar(input)
    invalidOptions('options must be a scalar struct.');
end
supported = {'collisionProfile', 'topologyProfile', ...
    'exactThreshold', 'nearMetricThreshold', ...
    'nearConditionThreshold', 'lowerBranchId', ...
    'lowerBranchMode', 'referenceQ', 'couplingReference'};
if ~all(ismember(fieldnames(input), supported))
    invalidOptions('options contains an unsupported field.');
end

options = struct( ...
    'collisionProfile', optionValue( ...
        input, 'collisionProfile', "centerline"), ...
    'topologyProfile', optionValue( ...
        input, 'topologyProfile', "reference"), ...
    'exactThreshold', optionValue(input, 'exactThreshold', 1e-8), ...
    'nearMetricThreshold', optionValue( ...
        input, 'nearMetricThreshold', 0.05), ...
    'nearConditionThreshold', optionValue( ...
        input, 'nearConditionThreshold', 100), ...
    'lowerBranchId', optionValue( ...
        input, 'lowerBranchId', geometry.assembly.defaultBranch), ...
    'lowerBranchMode', optionValue( ...
        input, 'lowerBranchMode', "fixed"), ...
    'referenceQ', optionValue( ...
        input, 'referenceQ', geometry.analysis.referenceQ), ...
    'couplingReference', optionValue( ...
        input, 'couplingReference', []));

options.collisionProfile = validatedText( ...
    options.collisionProfile, ...
    ["none", "centerline", "physicalClearance"], ...
    'collisionProfile is invalid.');
if options.collisionProfile == "physicalClearance"
    try
        duallink5.validation.validateCollisionConfiguration( ...
            options.collisionProfile, geometry.collision, true);
    catch exception
        if strcmp(exception.identifier, ...
                'duallink5:validation:MissingClearanceGeometry')
            invalidOptions( ...
                'physicalClearance geometry is incomplete.');
        end
        rethrow(exception)
    end
end
options.topologyProfile = validatedText( ...
    options.topologyProfile, ["reference", "none"], ...
    'topologyProfile must be reference or none.');
options.lowerBranchMode = validatedText( ...
    options.lowerBranchMode, "fixed", ...
    'lowerBranchMode must be fixed.');

if ~validScalar(options.exactThreshold) || options.exactThreshold < 0
    invalidOptions('exactThreshold must be nonnegative and finite.');
end
if ~validScalar(options.nearMetricThreshold) || ...
        options.nearMetricThreshold <= 0 || ...
        options.nearMetricThreshold >= 1
    invalidOptions('nearMetricThreshold must be strictly between 0 and 1.');
end
if options.exactThreshold >= options.nearMetricThreshold
    invalidOptions('exactThreshold must be less than nearMetricThreshold.');
end
if ~validScalar(options.nearConditionThreshold) || ...
        options.nearConditionThreshold <= 1
    invalidOptions('nearConditionThreshold must be greater than 1.');
end
if ~(isnumeric(options.lowerBranchId) && ...
        isreal(options.lowerBranchId) && ...
        isscalar(options.lowerBranchId) && ...
        isfinite(options.lowerBranchId) && ...
        ismember(double(options.lowerBranchId), [-1, 1]))
    invalidOptions('lowerBranchId must be -1 or +1.');
end
if ~validQ(options.referenceQ)
    invalidOptions('referenceQ must be a finite real numeric 1x2 vector.');
end

options.exactThreshold = double(options.exactThreshold);
options.nearMetricThreshold = double(options.nearMetricThreshold);
options.nearConditionThreshold = double(options.nearConditionThreshold);
options.lowerBranchId = int8(options.lowerBranchId);
options.referenceQ = full(double(options.referenceQ));
if ~isempty(options.couplingReference)
    options.couplingReference = validateReference( ...
        options.couplingReference, geometry);
    if ~isequal(options.couplingReference.q, options.referenceQ)
        invalidOptions( ...
            'referenceQ must match couplingReference.q.');
    end
end
end

function reference = validateReference(reference, geometry)
required = {'q', 'passiveOrientationSign', 'topology', ...
    'geometryVersion', 'geometryFingerprint', 'integrityToken'};
legacyRequired = {'q', 'passiveOrientationSign', 'topology', ...
    'geometryVersion'};
if ~isstruct(reference) || ~isscalar(reference)
    invalidOptions('couplingReference is malformed or incompatible.');
end
names = sort(fieldnames(reference));
if isequal(names, sort(legacyRequired(:)))
    reference.geometryFingerprint = struct();
    reference.integrityToken = "external-untrusted";
elseif ~isequal(names, sort(required(:)))
    invalidOptions('couplingReference is malformed or incompatible.');
end
if ~validQ(reference.q) || ...
        ~(isnumeric(reference.passiveOrientationSign) && ...
        isreal(reference.passiveOrientationSign) && ...
        isscalar(reference.passiveOrientationSign) && ...
        isfinite(reference.passiveOrientationSign) && ...
        ismember(double(reference.passiveOrientationSign), [-1, 1])) || ...
        ~validGeometryVersion(reference.geometryVersion, geometry.version) || ...
        ~validTopology(reference.topology) || ...
        ~isstruct(reference.geometryFingerprint) || ...
        ~isscalar(reference.geometryFingerprint) || ...
        ~validToken(reference.integrityToken)
    invalidOptions('couplingReference is malformed or incompatible.');
end
reference.q = full(double(reference.q));
reference.passiveOrientationSign = ...
    int8(reference.passiveOrientationSign);
reference.geometryVersion = string(reference.geometryVersion);
reference.integrityToken = string(reference.integrityToken);
reference.topology.lengthTolerance = ...
    double(reference.topology.lengthTolerance);
end

function valid = validToken(value)
try
    value = string(value);
    valid = isscalar(value) && ~ismissing(value) && strlength(value) > 0;
catch
    valid = false;
end
end

function valid = validTopology(topology)
required = {'signature', 'lengthTolerance'};
valid = isstruct(topology) && isscalar(topology) && ...
    isequal(sort(fieldnames(topology)), sort(required(:))) && ...
    isstring(topology.signature) && ismatrix(topology.signature) && ...
    size(topology.signature, 2) == 2 && ...
    ~any(ismissing(topology.signature), 'all') && ...
    validScalar(topology.lengthTolerance) && ...
    topology.lengthTolerance > 0;
if valid
    valid = validTopologySignature(topology.signature);
end
end

function valid = validTopologySignature(signature)
allowed = [ ...
    "lower.link1", "lower.link2", "lower.link3", ...
    "lower.link5", "shared.link4", ...
    "upper.link1", "upper.link2", "upper.link3", ...
    "upper.link5", ...
    "alpha.12", "alpha.23", "alpha.34", "alpha.41", ...
    "beta.12", "beta.23", "beta.34", "beta.41"];
if isempty(signature)
    valid = isequal(size(signature), [0, 2]);
    return
end
canonicalRows = sort(signature, 2);
valid = all(ismember(signature, allowed), 'all') && ...
    all(signature(:, 1) ~= signature(:, 2)) && ...
    isequal(signature, canonicalRows) && ...
    isequal(signature, sortrows(signature, [1, 2])) && ...
    size(unique(signature, 'rows'), 1) == size(signature, 1);
end

function valid = validGeometryVersion(value, expected)
try
    value = string(value);
    expected = string(expected);
    valid = isscalar(value) && ~ismissing(value) && ...
        strlength(value) > 0 && isequal(value, expected);
catch
    valid = false;
end
end

function value = validatedText(value, allowed, message)
try
    value = string(value);
catch
    invalidOptions(message);
end
if ~isscalar(value) || ismissing(value) || ~ismember(value, allowed)
    invalidOptions(message);
end
end

function valid = validScalar(value)
valid = isnumeric(value) && isreal(value) && isscalar(value) && ...
    isfinite(value);
end

function valid = validQ(q)
valid = isnumeric(q) && isreal(q) && isequal(size(q), [1, 2]) && ...
    all(isfinite(q));
end

function value = optionValue(options, name, defaultValue)
if isfield(options, name)
    value = options.(name);
else
    value = defaultValue;
end
end

function invalidOptions(message)
error('duallink5:singularity:InvalidCouplingOptions', message);
end
