function reference = prepareCouplingReference(options, geometry)
%PREPARECOUPLINGREFERENCE Build or reuse a regular passive reference.
persistent trustedReferences
if isempty(trustedReferences)
    trustedReferences = cell(0, 1);
end

fingerprint = geometryFingerprint(options, geometry);
if isempty(options.couplingReference)
    reference = buildReference(options, geometry, fingerprint);
    trustedReferences = registerReference(trustedReferences, reference);
    return
end

reference = options.couplingReference;
if reference.topology.lengthTolerance ~= geometry.tolerance.length
    invalidReference();
end
if ~isempty(fieldnames(reference.geometryFingerprint)) && ...
        ~isequal(reference.geometryFingerprint, fingerprint)
    invalidReference();
end
if ~isempty(fieldnames(reference.geometryFingerprint)) && ...
        trustedReference(reference, trustedReferences)
    return
end

expected = buildReference(options, geometry, fingerprint);
if ~semanticMatch(reference, expected)
    invalidReference();
end
trustedReferences = registerReference(trustedReferences, reference);
end

function reference = buildReference(options, geometry, fingerprint)

kinematics = duallink5.kinematics.forwardPassiveDoublet( ...
    options.referenceQ, geometry, struct( ...
    'collisionProfile', "none", ...
    'lowerBranchMode', options.lowerBranchMode, ...
    'lowerBranchId', options.lowerBranchId));
if ~kinematics.quality.valid || ...
        kinematics.quality.statusCode ~= "OK" || ...
        kinematics.quality.closureStatusCode ~= "OK" || ...
        ~ismember(double( ...
        kinematics.quality.passiveOrientationSign), [-1, 1])
    error('duallink5:singularity:InvalidCouplingOptions', ...
        'referenceQ must resolve to a regular passive assembly.');
end

try
    topology = ...
        duallink5.validation.prepareAssemblyTopologyReference( ...
        kinematics, geometry.tolerance.length);
catch exception
    if strcmp(exception.identifier, ...
            'duallink5:validation:InvalidAssemblyTopology')
        error('duallink5:singularity:InvalidCouplingOptions', ...
            'referenceQ must define a complete assembly topology.');
    end
    rethrow(exception)
end
reference = struct( ...
    'q', options.referenceQ, ...
    'passiveOrientationSign', int8( ...
        kinematics.quality.passiveOrientationSign), ...
    'topology', topology, ...
    'geometryVersion', string(geometry.version), ...
    'geometryFingerprint', fingerprint, ...
    'integrityToken', newToken());
end

function fingerprint = geometryFingerprint(options, geometry)
fingerprint = struct( ...
    'links', geometry.links, ...
    'parallelLengths', geometry.parallel.lengths, ...
    'parallelDirections', geometry.parallel.direction, ...
    'defaultBranch', int8(geometry.assembly.defaultBranch), ...
    'lowerBranchId', options.lowerBranchId, ...
    'tolerances', geometry.tolerance, ...
    'referenceQ', options.referenceQ, ...
    'geometryVersion', string(geometry.version));
end

function valid = semanticMatch(reference, expected)
valid = isequal(reference.q, expected.q) && ...
    reference.passiveOrientationSign == ...
    expected.passiveOrientationSign && ...
    isequal(reference.topology, expected.topology) && ...
    isequal(reference.geometryVersion, expected.geometryVersion) && ...
    (isempty(fieldnames(reference.geometryFingerprint)) || ...
    isequal(reference.geometryFingerprint, expected.geometryFingerprint));
end

function valid = trustedReference(reference, trustedReferences)
valid = false;
for index = 1:numel(trustedReferences)
    trusted = trustedReferences{index};
    if reference.integrityToken == trusted.integrityToken
        valid = isequal(reference, trusted);
        return
    end
end
end

function references = registerReference(references, reference)
references{end + 1, 1} = reference;
if numel(references) > 32
    references = references(end - 31:end);
end
end

function token = newToken()
token = string(char(java.util.UUID.randomUUID));
end

function invalidReference()
error('duallink5:singularity:InvalidCouplingOptions', ...
    'couplingReference does not match the current reference semantics.');
end
