function reference = prepareTopologyReference(geometry, options)
reference = [];
if options.topologyProfile == "none"
    return
end
referenceQ = geometry.analysis.referenceQ;
input = struct('lower', referenceQ, 'upper', referenceQ);
assemblyOptions = struct( ...
    'mode', "ideal", ...
    'branchMode', "fixed", ...
    'branchId', options.branchId, ...
    'collisionProfile', options.collisionProfile);
assembly = duallink5.kinematics.forwardAssembly( ...
    input, geometry, assemblyOptions);
if ~assembly.quality.valid
    error('duallink5:singularity:InvalidOptions', ...
        'The configured reference assembly is invalid for these options.');
end
reference = duallink5.validation.prepareAssemblyTopologyReference( ...
    assembly, geometry.tolerance.length);
end
