function handles = plotCouplingSingularitySpace( ...
        samples, axesHandles, options)
%PLOTCOUPLINGSINGULARITYSPACE Plot coupling risk and representative poses.
if nargin < 3
    options = struct();
end
[axesHandles, options] = validateInputs(samples, axesHandles, options);
originalNextPlot = string({axesHandles.NextPlot});
cleanup = onCleanup(@()restoreAxes(axesHandles, originalNextPlot));
set(axesHandles, 'NextPlot', 'add');

thetaDegrees = rad2deg(samples.thetaGrid(:, 1));
phiDegrees = rad2deg(samples.phiGrid(1, :));
thetaEdges = cellEdges(thetaDegrees);
phiEdges = cellEdges(phiDegrees);
[thetaEdgeGrid, phiEdgeGrid] = meshgrid(thetaEdges, phiEdges);
[riskData, colorLimits] = finiteRisk(samples);

handles = struct();
handles.riskData = riskData;
handles.jointMap = plotCellMap(axesHandles(1), thetaEdgeGrid, ...
    phiEdgeGrid, riskData.');
set(axesHandles(1), 'YDir', 'normal');
colormap(axesHandles(1), turbo(256));
clim(axesHandles(1), colorLimits);
handles.unreachableMask = plotMaskLayer(axesHandles(1), ...
    thetaEdgeGrid, phiEdgeGrid, ...
    (~samples.theoreticalReachableMask).', [0.68, 0.68, 0.68], ...
    'theoretically unreachable');
warningDegrees = rad2deg(samples.metadata.couplingWarningAngle);
handles.warningBand = patch(axesHandles(1), ...
    thetaEdges([1, end, end, 1]), ...
    [-warningDegrees, -warningDegrees, warningDegrees, warningDegrees], ...
    [1.00, 0.72, 0.18], 'FaceAlpha', 0.15, 'EdgeColor', 'none', ...
    'DisplayName', 'engineering warning band');
handles.theoreticalLine = plot(axesHandles(1), thetaEdges([1, end]), ...
    [0, 0], '-', 'Color', [0.80, 0.08, 0.12], 'LineWidth', 2, ...
    'DisplayName', '\phi = 0 deg theoretical singularity');
handles.warningBoundaries = gobjects(1, 2);
handles.warningBoundaries(1) = plot(axesHandles(1), ...
    thetaEdges([1, end]), [-warningDegrees, -warningDegrees], '--', ...
    'Color', [0.92, 0.48, 0.05], 'LineWidth', 1.4, ...
    'DisplayName', '- warning boundary');
handles.warningBoundaries(2) = plot(axesHandles(1), ...
    thetaEdges([1, end]), [warningDegrees, warningDegrees], '--', ...
    'Color', [0.92, 0.48, 0.05], 'LineWidth', 1.4, ...
    'DisplayName', '+ warning boundary');
invalid = ~samples.mechanicallyValidMask & ...
    samples.theoreticalReachableMask;
handles.invalidJoint = scatter(axesHandles(1), ...
    rad2deg(samples.thetaGrid(invalid)), ...
    rad2deg(samples.phiGrid(invalid)), 24, [0.45, 0.45, 0.45], ...
    'x', 'LineWidth', 1.2, 'DisplayName', 'mechanically invalid');
referenceDegrees = rad2deg(samples.metadata.referenceQ);
handles.reference = plot(axesHandles(1), referenceDegrees(1), ...
    referenceDegrees(2), 'wo', 'MarkerEdgeColor', [0.08, 0.10, 0.14], ...
    'MarkerFaceColor', 'w', 'LineWidth', 1.3, 'MarkerSize', 7, ...
    'DisplayName', 'reference');
xlim(axesHandles(1), thetaEdges([1, end]));
ylim(axesHandles(1), [min(phiEdges(1), -1.1 * warningDegrees), ...
    max(phiEdges(end), 1.1 * warningDegrees)]);
xlabel(axesHandles(1), '\theta [deg]');
ylabel(axesHandles(1), '\phi [deg]');
title(axesHandles(1), 'Doublet coupling risk in joint space');
grid(axesHandles(1), 'on');
handles.jointColorbar = colorbar(axesHandles(1));
handles.jointColorbar.Label.String = 'log_{10} coupling condition number';
handles.legend = legend(axesHandles(1), ...
    [handles.theoreticalLine, handles.warningBoundaries(1), ...
    handles.warningBand, handles.unreachableMask, ...
    handles.invalidJoint, handles.reference], ...
    'Location', 'best');

theoretical = samples.theoreticalReachableMask;
handles.taskScatter = scatter(axesHandles(2), ...
    1e3 * samples.x(theoretical), 1e3 * samples.y(theoretical), ...
    18, riskData(theoretical), 'filled', ...
    'MarkerFaceAlpha', 0.72, 'MarkerEdgeAlpha', 0.22);
colormap(axesHandles(2), turbo(256));
clim(axesHandles(2), colorLimits);
exact = samples.exactCouplingSingular & theoretical;
handles.taskExact = scatter(axesHandles(2), 1e3 * samples.x(exact), ...
    1e3 * samples.y(exact), 34, [0.80, 0.08, 0.12], 'o', ...
    'LineWidth', 1.3);
warning = samples.engineeringWarning & theoretical & ~exact;
handles.taskWarning = scatter(axesHandles(2), ...
    1e3 * samples.x(warning), 1e3 * samples.y(warning), ...
    18, [0.92, 0.48, 0.05], 'o', 'LineWidth', 0.8);
xlabel(axesHandles(2), 'x_G [mm]');
ylabel(axesHandles(2), 'y_G [mm]');
title(axesHandles(2), 'Doublet coupling risk in task space');
axis(axesHandles(2), 'equal');
grid(axesHandles(2), 'on');
handles.taskColorbar = colorbar(axesHandles(2));
handles.taskColorbar.Label.String = 'log_{10} coupling condition number';

[indices, results, sourceDirections, status, representativeQ, ...
    poseTitles] = representativeResults( ...
    samples, options);
handles.representativeIndices = indices;
handles.sourceDirections = sourceDirections;
handles.representativeStatus = status;
handles.representativeQ = representativeQ;
handles.representativeDirections = zeros(2, 3);
handles.poseArrows = gobjects(3, 2);
assemblyHandles = cell(3, 1);
allX = zeros(1, 0);
allY = zeros(1, 0);
for index = 1:3
    assemblyHandles{index} = duallink5.viz.plotAssembly( ...
        results{index}.kinematics, axesHandles(index + 2), ...
        struct('showLabels', false));
    direction = unitDirection(results{index}.coupling.passiveDirection);
    handles.representativeDirections(:, index) = direction;
    G = 1e3 * results{index}.kinematics.points.G(:);
    delta = options.arrowLengthMm * direction;
    handles.poseArrows(index, 1) = quiver(axesHandles(index + 2), ...
        G(1), G(2), delta(1), delta(2), 0, ...
        'Color', [0.72, 0.08, 0.48], 'LineWidth', 1.8, ...
        'MaxHeadSize', 0.7);
    handles.poseArrows(index, 2) = quiver(axesHandles(index + 2), ...
        G(1), G(2), -delta(1), -delta(2), 0, ...
        'Color', [0.72, 0.08, 0.48], 'LineWidth', 1.8, ...
        'MaxHeadSize', 0.7);
    title(axesHandles(index + 2), poseTitles(index));
    [poseX, poseY] = assemblyCoordinates(results{index}.kinematics);
    allX = [allX, poseX, G(1) + [-delta(1), delta(1)]]; %#ok<AGROW>
    allY = [allY, poseY, G(2) + [-delta(2), delta(2)]]; %#ok<AGROW>
end
handles.assemblies = vertcat(assemblyHandles{:});
[commonX, commonY] = commonLimits(allX, allY);
for index = 3:5
    xlim(axesHandles(index), commonX);
    ylim(axesHandles(index), commonY);
    grid(axesHandles(index), 'on');
end
preventRepresentativeTextOverlap(axesHandles(3:5));
clear cleanup
end

function preventRepresentativeTextOverlap(axesHandles)
if any(arrayfun(@(item)isa(item.Parent, ...
        'matlab.graphics.layout.TiledChartLayout'), axesHandles))
    return
end
figureHandle = ancestor(axesHandles(1), 'figure');
if isempty(figureHandle) || any(arrayfun( ...
        @(item)ancestor(item, 'figure') ~= figureHandle, axesHandles))
    return
end
drawnow;
minimumGapPixels = 6;
for lowerIndex = 2:numel(axesHandles)
    for attempt = 1:3
        upperLabel = figureTextBounds( ...
            axesHandles(lowerIndex - 1).XLabel);
        lowerTitle = figureTextBounds( ...
            axesHandles(lowerIndex).Title);
        gap = upperLabel(2) - (lowerTitle(2) + lowerTitle(4));
        deficit = minimumGapPixels - gap;
        if deficit <= 0.01
            break
        end
        shiftAxesPixels(axesHandles(lowerIndex:end), -deficit);
        drawnow;
    end
end
keepRepresentativeAxesOnCanvas(axesHandles, figureHandle);
end

function keepRepresentativeAxesOnCanvas(axesHandles, figureHandle)
canvasMarginPixels = 2;
figurePosition = getpixelposition(figureHandle);
[minimumBottom, maximumTop] = representativeVerticalBounds( ...
    axesHandles);
minimumShift = canvasMarginPixels - minimumBottom;
maximumShift = figurePosition(4) - canvasMarginPixels - maximumTop;
if minimumShift <= maximumShift
    shift = min(max(0, minimumShift), maximumShift);
else
    shift = minimumShift;
end
if abs(shift) > 0.01
    shiftAxesPixels(axesHandles, shift);
    drawnow;
end
end

function [minimumBottom, maximumTop] = representativeVerticalBounds( ...
        axesHandles)
minimumBottom = Inf;
maximumTop = -Inf;
for index = 1:numel(axesHandles)
    axesPosition = getpixelposition(axesHandles(index), true);
    labelBounds = figureTextBounds( ...
        axesHandles(index).XLabel);
    titleBounds = figureTextBounds( ...
        axesHandles(index).Title);
    minimumBottom = min([minimumBottom, axesPosition(2), ...
        labelBounds(2), titleBounds(2)]);
    maximumTop = max([maximumTop, axesPosition(2) + axesPosition(4), ...
        labelBounds(2) + labelBounds(4), ...
        titleBounds(2) + titleBounds(4)]);
end
end

function shiftAxesPixels(axesHandles, verticalShift)
for index = 1:numel(axesHandles)
    position = getpixelposition(axesHandles(index), true);
    position(2) = position(2) + verticalShift;
    setpixelposition(axesHandles(index), position, true);
end
end

function bounds = figureTextBounds(textHandle)
originalUnits = textHandle.Units;
unitCleanup = onCleanup(@()set(textHandle, 'Units', originalUnits));
textHandle.Units = 'pixels';
bounds = textHandle.Extent;
axesPosition = getpixelposition(textHandle.Parent, true);
bounds(1:2) = bounds(1:2) + axesPosition(1:2);
clear unitCleanup
end

function [axesHandles, options] = validateInputs( ...
        samples, axesHandles, options)
try
    axesHandles = validateAxes(axesHandles);
    options = validateOptions(options);
    validateSamples(samples, options.geometry);
catch exception
    if strcmp(exception.identifier, ...
            'duallink5:viz:InvalidCouplingPlotInput')
        rethrow(exception)
    end
    invalidInput();
end
end

function axesHandles = validateAxes(axesHandles)
if ~isvector(axesHandles) || numel(axesHandles) ~= 5 || ...
        ~all(isgraphics(axesHandles, 'axes'), 'all')
    invalidInput();
end
axesHandles = axesHandles(:).';
for first = 1:4
    for second = first + 1:5
        if isequal(axesHandles(first), axesHandles(second))
            invalidInput();
        end
    end
end
end

function options = validateOptions(input)
if ~isstruct(input) || ~isscalar(input) || ...
        ~all(ismember(fieldnames(input), ...
        {'geometry', 'representativeQ', 'arrowLengthMm'}))
    invalidInput();
end
if isfield(input, 'geometry')
    geometry = input.geometry;
else
    geometry = duallink5.model.defaultGeometry();
end
geometry = duallink5.model.validateGeometry(geometry);
if isfield(input, 'representativeQ')
    representativeQ = input.representativeQ;
else
    representativeQ = deg2rad([85, 30; 85, 10; 85, 0]);
end
if ~(isnumeric(representativeQ) && isreal(representativeQ) && ...
        isequal(size(representativeQ), [3, 2]) && ...
        all(isfinite(representativeQ), 'all'))
    invalidInput();
end
if isfield(input, 'arrowLengthMm')
    arrowLengthMm = input.arrowLengthMm;
else
    arrowLengthMm = 18;
end
if ~(isnumeric(arrowLengthMm) && isreal(arrowLengthMm) && ...
        isscalar(arrowLengthMm) && isfinite(arrowLengthMm) && ...
        arrowLengthMm > 0)
    invalidInput();
end
options = struct('geometry', geometry, ...
    'representativeQ', full(double(representativeQ)), ...
    'arrowLengthMm', full(double(arrowLengthMm)));
end

function validateSamples(samples, geometry)
required = {'thetaGrid', 'phiGrid', 'x', 'y', 'couplingMargin', ...
    'sigmaMin', 'conditionNumber', 'constraintMatrix', ...
    'actuationMatrix', 'taskJacobian', 'passiveDirection', ...
    'theoreticalReachableMask', 'mechanicallyValidMask', ...
    'exactCouplingSingular', 'nearCouplingSingular', ...
    'engineeringWarning', 'safeUsableMask', 'reasonMap', ...
    'assemblyStatusMap', 'passiveOrientationSign', ...
    'lowerClosureSingular', 'metadata'};
if ~isstruct(samples) || ~isscalar(samples) || ...
        ~all(isfield(samples, required))
    invalidInput();
end
shape = size(samples.thetaGrid);
validGrid = validNumericMap(samples.thetaGrid, shape) && ...
    ~isempty(samples.thetaGrid) && all(isfinite(samples.thetaGrid), 'all') && ...
    validNumericMap(samples.phiGrid, shape) && ...
    all(isfinite(samples.phiGrid), 'all') && ...
    validGridStructure(samples.thetaGrid, samples.phiGrid);
numericNames = {'x', 'y', 'couplingMargin', 'sigmaMin', ...
    'conditionNumber', 'passiveOrientationSign'};
logicalNames = {'theoreticalReachableMask', 'mechanicallyValidMask', ...
    'exactCouplingSingular', 'nearCouplingSingular', ...
    'engineeringWarning', 'safeUsableMask', 'lowerClosureSingular'};
validMaps = all(cellfun(@(name)validNumericMap( ...
    samples.(name), shape), numericNames)) && ...
    all(cellfun(@(name)islogical(samples.(name)) && ...
    isequal(size(samples.(name)), shape), logicalNames)) && ...
    validStringMap(samples.reasonMap, shape) && ...
    validStringMap(samples.assemblyStatusMap, shape);
validTensors = validTensor(samples.constraintMatrix, shape, 4) && ...
    validTensor(samples.actuationMatrix, shape, 4) && ...
    validTensor(samples.taskJacobian, shape, 4) && ...
    validTensor(samples.passiveDirection, shape, 2);
if ~(validGrid && validMaps && validTensors)
    invalidInput();
end

theoretical = samples.theoreticalReachableMask;
mechanical = samples.mechanicallyValidMask;
exact = samples.exactCouplingSingular;
near = samples.nearCouplingSingular;
warning = samples.engineeringWarning;
safe = samples.safeUsableMask;
if ~any(theoretical, 'all') || ...
        any(mechanical & ~theoretical, 'all') || ...
        any(safe & (~mechanical | near | warning | exact), 'all') || ...
        any(exact & ~theoretical, 'all') || ...
        any(exact & ~near, 'all') || ...
        any(samples.lowerClosureSingular & ~theoretical, 'all') || ...
        any(near & ~theoretical, 'all') || ...
        any(~isnan(samples.x(~theoretical)), 'all') || ...
        any(~isnan(samples.y(~theoretical)), 'all') || ...
        any(~isfinite(samples.x(theoretical)), 'all') || ...
        any(~isfinite(samples.y(theoretical)), 'all')
    invalidInput();
end
condition = samples.conditionNumber(theoretical);
if any(isnan(condition) | condition <= 0, 'all') || ...
        any(condition == -Inf, 'all') || ...
        any(~isnan(samples.conditionNumber(~theoretical)), 'all')
    invalidInput();
end
if any(~isfinite(samples.couplingMargin(theoretical)), 'all') || ...
        any(samples.couplingMargin(theoretical) < 0 | ...
        samples.couplingMargin(theoretical) > 1, 'all') || ...
        any(~isfinite(samples.sigmaMin(theoretical)), 'all') || ...
        any(samples.sigmaMin(theoretical) < 0, 'all')
    invalidInput();
end
directions = reshape(samples.passiveDirection, 2, []);
theoreticalDirections = directions(:, theoretical(:));
if ~isempty(theoreticalDirections) && ...
        (~all(isfinite(theoreticalDirections), 'all') || ...
        any(abs(vecnorm(theoreticalDirections) - 1) > 1e-6, 'all'))
    invalidInput();
end
signs = samples.passiveOrientationSign(theoretical);
if any(~isfinite(signs) | ~ismember(signs, [-1, 0, 1]), 'all')
    invalidInput();
end
validateReasons(samples);
validateMetadata(samples.metadata, geometry, shape);
end

function valid = validNumericMap(value, shape)
valid = isnumeric(value) && isreal(value) && ismatrix(value) && ...
    isequal(size(value), shape);
end

function valid = validStringMap(value, shape)
valid = isstring(value) && isequal(size(value), shape) && ...
    ~any(ismissing(value), 'all') && ...
    ~any(strlength(value) == 0, 'all');
end

function valid = validTensor(value, shape, leadingCount)
actualSize = size(value);
expectedSize = [2, shape];
if leadingCount == 4
    expectedSize = [2, 2, shape];
end
actualSize(end + 1:numel(expectedSize)) = 1;
expectedSize(end + 1:numel(actualSize)) = 1;
valid = isnumeric(value) && isreal(value) && ...
    isequal(actualSize, expectedSize);
if leadingCount == 4
    valid = valid && size(value, 2) == 2;
end
end

function valid = validGridStructure(thetaGrid, phiGrid)
theta = thetaGrid(:, 1);
phi = phiGrid(1, :);
valid = all(diff(double(theta)) > 0) && ...
    all(diff(double(phi)) > 0) && ...
    all(thetaGrid == theta, 'all') && all(phiGrid == phi, 'all');
end

function validateReasons(samples)
reason = samples.reasonMap;
assembly = samples.assemblyStatusMap;
theoretical = samples.theoreticalReachableMask;
mechanical = samples.mechanicallyValidMask;
exact = samples.exactCouplingSingular;
nearOnly = samples.nearCouplingSingular & ~exact;
warningOnly = samples.engineeringWarning & ...
    ~samples.nearCouplingSingular;
safe = samples.safeUsableMask;
mechanicalFailure = ["JOINT_LIMIT_VIOLATION", ...
    "PASSIVE_ASSEMBLY_TOPOLOGY_MISMATCH", ...
    "ASSEMBLY_TOPOLOGY_MISMATCH", "SELF_COLLISION", ...
    "PARALLEL_SHARED_COLLISION"];
theoreticalFailure = ["UNREACHABLE_CLOSURE", ...
    "UNREACHABLE_PASSIVE_CLOSURE", "COINCIDENT_CIRCLES", ...
    "NUMERICAL_CLOSURE_FAILURE", "BRANCH_DISCONTINUITY", ...
    "NO_VALID_BRANCH", "NEAR_SINGULAR", ...
    "INTERNAL_TANGENCY", "EXTERNAL_TANGENCY"];
validReasons = ["OK", "COUPLING_SINGULAR", ...
    "NEAR_COUPLING_SINGULAR", "ENGINEERING_WARNING", ...
    "LOWER_CLOSURE_SINGULAR", mechanicalFailure, theoreticalFailure];
validAssembly = ["OK", mechanicalFailure, theoreticalFailure];
invalidMechanical = theoretical & ~mechanical;
lowerSingular = samples.lowerClosureSingular;
if any(~ismember(reason, validReasons), 'all') || ...
        any(~ismember(assembly, validAssembly), 'all') || ...
        any(~theoretical & ~ismember(reason, theoreticalFailure), 'all') || ...
        any(~theoretical & assembly ~= reason, 'all') || ...
        any(mechanical & assembly ~= "OK", 'all') || ...
        any(invalidMechanical & ~ismember(assembly, mechanicalFailure), 'all') || ...
        any(invalidMechanical & ~exact & reason ~= assembly, 'all') || ...
        any(exact & reason ~= "COUPLING_SINGULAR", 'all') || ...
        any(lowerSingular & reason ~= "LOWER_CLOSURE_SINGULAR", 'all') || ...
        any(nearOnly & mechanical & ...
        reason ~= "NEAR_COUPLING_SINGULAR", 'all') || ...
        any(warningOnly & mechanical & ...
        reason ~= "ENGINEERING_WARNING", 'all') || ...
        any(safe & reason ~= "OK", 'all') || ...
        any(~theoretical & (mechanical | safe | exact), 'all') || ...
        any(~mechanical & reason == "OK", 'all')
    invalidInput();
end
end

function validateMetadata(metadata, geometry, shape)
required = {'units', 'storageLengthUnit', 'storageAngleUnit', ...
    'displayLengthUnit', 'displayAngleUnit', ...
    'couplingWarningAngle', 'exactThreshold', ...
    'nearMetricThreshold', 'nearConditionThreshold', 'referenceQ', ...
    'couplingReference', 'geometryFingerprint', ...
    'referencePassiveOrientationSign', ...
    'referenceSign', 'branchId', 'lowerBranchId', 'lowerBranchMode', ...
    'collisionProfile', 'topologyProfile', 'geometryVersion', ...
    'gridShape'};
if ~isstruct(metadata) || ~isscalar(metadata) || ...
        ~all(isfield(metadata, required)) || ...
        ~isstruct(metadata.units) || ~isscalar(metadata.units) || ...
        ~all(isfield(metadata.units, {'length', 'angle'})) || ...
        ~validText(metadata.units.length, "m") || ...
        ~validText(metadata.units.angle, "rad") || ...
        ~validText(metadata.storageLengthUnit, "m") || ...
        ~validText(metadata.storageAngleUnit, "rad") || ...
        ~validText(metadata.displayLengthUnit, "mm") || ...
        ~validText(metadata.displayAngleUnit, "deg") || ...
        ~validPositiveScalar(metadata.couplingWarningAngle) || ...
        metadata.couplingWarningAngle >= pi / 2 || ...
        ~validNonnegativeScalar(metadata.exactThreshold) || ...
        ~validPositiveScalar(metadata.nearMetricThreshold) || ...
        metadata.nearMetricThreshold >= 1 || ...
        metadata.exactThreshold >= metadata.nearMetricThreshold || ...
        ~validPositiveScalar(metadata.nearConditionThreshold) || ...
        metadata.nearConditionThreshold <= 1 || ...
        ~(isnumeric(metadata.referenceQ) && isreal(metadata.referenceQ) && ...
        isequal(size(metadata.referenceQ), [1, 2]) && ...
        all(isfinite(metadata.referenceQ), 'all')) || ...
        ~validCouplingReference(metadata.couplingReference, geometry) || ...
        ~isstruct(metadata.geometryFingerprint) || ...
        ~isscalar(metadata.geometryFingerprint) || ...
        ~isequal(metadata.geometryFingerprint, ...
        metadata.couplingReference.geometryFingerprint) || ...
        ~isequal(metadata.geometryFingerprint, ...
        expectedGeometryFingerprint(metadata, geometry)) || ...
        ~(isnumeric(metadata.referencePassiveOrientationSign) && ...
        isreal(metadata.referencePassiveOrientationSign) && ...
        isscalar(metadata.referencePassiveOrientationSign) && ...
        ismember(double(metadata.referencePassiveOrientationSign), [-1, 1])) || ...
        ~(isnumeric(metadata.referenceSign) && ...
        isreal(metadata.referenceSign) && isscalar(metadata.referenceSign) && ...
        metadata.referenceSign == ...
        metadata.referencePassiveOrientationSign) || ...
        ~(isnumeric(metadata.branchId) && isreal(metadata.branchId) && ...
        isscalar(metadata.branchId) && ...
        ismember(double(metadata.branchId), [-1, 1])) || ...
        ~(isnumeric(metadata.lowerBranchId) && ...
        isreal(metadata.lowerBranchId) && isscalar(metadata.lowerBranchId) && ...
        ismember(double(metadata.lowerBranchId), [-1, 1])) || ...
        ~validText(metadata.lowerBranchMode, "fixed") || ...
        ~validText(metadata.collisionProfile, ...
        ["none", "centerline", "physicalClearance"]) || ...
        ~validText(metadata.topologyProfile, ["none", "reference"]) || ...
        ~validText(metadata.geometryVersion, string(geometry.version)) || ...
        ~(isnumeric(metadata.gridShape) && isreal(metadata.gridShape) && ...
        isequal(double(metadata.gridShape), double(shape)))
    invalidInput();
end
end

function fingerprint = expectedGeometryFingerprint(metadata, geometry)
fingerprint = struct( ...
    'links', geometry.links, ...
    'parallelLengths', geometry.parallel.lengths, ...
    'parallelDirections', geometry.parallel.direction, ...
    'defaultBranch', int8(geometry.assembly.defaultBranch), ...
    'lowerBranchId', int8(metadata.lowerBranchId), ...
    'tolerances', geometry.tolerance, ...
    'referenceQ', full(double(metadata.referenceQ)), ...
    'geometryVersion', string(geometry.version));
end

function valid = validCouplingReference(reference, geometry)
required = {'q', 'passiveOrientationSign', 'topology', ...
    'geometryVersion'};
valid = isstruct(reference) && isscalar(reference) && ...
    all(isfield(reference, required));
if ~valid
    return
end
q = reference.q;
signValue = reference.passiveOrientationSign;
topology = reference.topology;
valid = isnumeric(q) && isreal(q) && isequal(size(q), [1, 2]) && ...
    all(isfinite(q), 'all') && ...
    isnumeric(signValue) && isreal(signValue) && isscalar(signValue) && ...
    isfinite(signValue) && ismember(double(signValue), [-1, 1]) && ...
    validText(reference.geometryVersion, string(geometry.version)) && ...
    isstruct(topology) && isscalar(topology) && ...
    all(isfield(topology, {'signature', 'lengthTolerance'})) && ...
    isstring(topology.signature) && ismatrix(topology.signature) && ...
    size(topology.signature, 2) == 2 && ...
    ~any(ismissing(topology.signature), 'all') && ...
    validPositiveScalar(topology.lengthTolerance);
end

function valid = validText(value, allowed)
try
    value = string(value);
    valid = isscalar(value) && ~ismissing(value) && ismember(value, allowed);
catch
    valid = false;
end
end

function valid = validPositiveScalar(value)
valid = isnumeric(value) && isreal(value) && isscalar(value) && ...
    isfinite(value) && value > 0;
end

function valid = validNonnegativeScalar(value)
valid = isnumeric(value) && isreal(value) && isscalar(value) && ...
    isfinite(value) && value >= 0;
end

function [riskData, limits] = finiteRisk(samples)
riskData = nan(size(samples.conditionNumber));
theoretical = samples.theoreticalReachableMask;
raw = log10(samples.conditionNumber(theoretical));
finiteValues = raw(isfinite(raw));
if isempty(finiteValues)
    cap = 1;
else
    spread = max(finiteValues) - min(finiteValues);
    cap = max(finiteValues) + max(0.25, 0.05 * spread);
end
raw(isinf(raw)) = cap;
riskData(theoretical) = raw;
values = riskData(theoretical);
minimum = min(values);
maximum = max(values);
if minimum < maximum
    limits = [minimum, maximum];
else
    padding = max(0.5, 0.05 * max(1, abs(minimum)));
    limits = minimum + [-padding, padding];
end
end

function edges = cellEdges(values)
centers = double(values(:).');
if isscalar(centers)
    halfWidth = max(1, 0.01 * abs(centers));
    edges = centers + [-halfWidth, halfWidth];
    return
end
halfSpacing = 0.5 * diff(centers);
edges = [centers(1) - halfSpacing(1), ...
    centers(1:end - 1) + halfSpacing, ...
    centers(end) + halfSpacing(end)];
end

function handle = plotCellMap(axesHandle, xEdges, yEdges, faceData)
rows = [1:size(faceData, 1), size(faceData, 1)];
columns = [1:size(faceData, 2), size(faceData, 2)];
paddedData = faceData(rows, columns);
handle = surface(axesHandle, xEdges, yEdges, ...
    zeros(size(paddedData)), paddedData, ...
    'FaceColor', 'flat', 'EdgeColor', 'none');
view(axesHandle, 2);
end

function handle = plotMaskLayer( ...
        axesHandle, xEdges, yEdges, mask, color, displayName)
rows = [1:size(mask, 1), size(mask, 1)];
columns = [1:size(mask, 2), size(mask, 2)];
paddedMask = double(mask(rows, columns));
handle = surface(axesHandle, xEdges, yEdges, ...
    ones(size(paddedMask)), paddedMask, ...
    'FaceColor', color, 'FaceAlpha', 'flat', ...
    'AlphaData', paddedMask, 'AlphaDataMapping', 'none', ...
    'EdgeColor', 'none', 'DisplayName', displayName);
view(axesHandle, 2);
end

function [indices, results, sourceDirections, status, selectedQ, titles] = ...
        representativeResults( ...
        samples, options)
available = find(samples.theoreticalReachableMask);
if isempty(available)
    invalidInput();
end
indices = zeros(3, 1);
results = cell(3, 1);
sourceDirections = zeros(2, 3);
status = strings(3, 1);
selectedQ = zeros(3, 2);
titles = strings(3, 1);
sourceTensor = reshape(samples.passiveDirection, 2, []);
for index = 1:3
    [candidates, preferred] = representativeCandidates(samples, index);
    if isempty(candidates)
        candidates = available;
        preferred = false;
    end
    difference = [samples.thetaGrid(candidates) - ...
        options.representativeQ(index, 1), ...
        samples.phiGrid(candidates) - options.representativeQ(index, 2)];
    [~, localIndex] = min(sum(difference .^ 2, 2));
    indices(index) = candidates(localIndex);
    sourceDirections(:, index) = unitDirection( ...
        sourceTensor(:, indices(index)));
    q = [samples.thetaGrid(indices(index)), ...
        samples.phiGrid(indices(index))];
    selectedQ(index, :) = q;
    status(index) = samples.reasonMap(indices(index));
    titles(index) = representativeTitle(samples, indices(index), preferred);
    couplingOptions = struct( ...
        'collisionProfile', "none", 'topologyProfile', "none", ...
        'exactThreshold', samples.metadata.exactThreshold, ...
        'nearMetricThreshold', samples.metadata.nearMetricThreshold, ...
        'nearConditionThreshold', samples.metadata.nearConditionThreshold, ...
        'lowerBranchId', samples.metadata.lowerBranchId, ...
        'lowerBranchMode', "fixed", ...
        'referenceQ', samples.metadata.referenceQ);
    try
        result = duallink5.singularity.evaluateCoupling( ...
            q, options.geometry, couplingOptions);
    catch
        invalidInput();
    end
    if ~result.theoreticallyReachable || ...
            ~result.kinematics.quality.valid
        invalidInput();
    end
    unitDirection(result.coupling.passiveDirection);
    results{index} = result;
end
end

function [candidates, preferred] = representativeCandidates(samples, slot)
theoretical = samples.theoreticalReachableMask;
switch slot
    case 1
        mask = theoretical & samples.mechanicallyValidMask & ...
            ~samples.exactCouplingSingular & ...
            ~samples.nearCouplingSingular & ...
            ~samples.engineeringWarning;
    case 2
        mask = theoretical & samples.mechanicallyValidMask & ...
            samples.engineeringWarning & ~samples.exactCouplingSingular;
        if ~any(mask, 'all')
            mask = theoretical & samples.engineeringWarning & ...
                ~samples.exactCouplingSingular;
        end
    otherwise
        mask = theoretical & samples.exactCouplingSingular;
end
candidates = find(mask);
preferred = ~isempty(candidates);
end

function plotTitle = representativeTitle(samples, index, preferred)
if samples.exactCouplingSingular(index)
    label = "Exact coupling singularity";
elseif samples.nearCouplingSingular(index)
    label = "Near coupling singularity";
elseif samples.engineeringWarning(index)
    label = "Engineering warning";
elseif samples.safeUsableMask(index)
    label = "Regular";
elseif ~samples.mechanicallyValidMask(index)
    label = replace(lower(samples.reasonMap(index)), "_", " ");
    label = upper(extractBefore(label, 2)) + extractAfter(label, 1);
else
    label = "Theoretical configuration";
end
if preferred
    plotTitle = label + " representative";
else
    plotTitle = label + " (closest available)";
end
end

function direction = unitDirection(direction)
if ~(isnumeric(direction) && isreal(direction) && ...
        numel(direction) == 2 && all(isfinite(direction), 'all'))
    invalidInput();
end
direction = full(double(direction(:)));
magnitude = norm(direction);
if ~isfinite(magnitude) || magnitude < 1e-12
    invalidInput();
end
direction = direction / magnitude;
end

function [xValues, yValues] = assemblyCoordinates(assembly)
xValues = zeros(1, 0);
yValues = zeros(1, 0);
poses = {assembly.lower.points, assembly.upper.points};
for poseIndex = 1:numel(poses)
    names = fieldnames(poses{poseIndex});
    for nameIndex = 1:numel(names)
        point = poses{poseIndex}.(names{nameIndex});
        if isnumeric(point) && isreal(point) && numel(point) == 2 && ...
                all(isfinite(point), 'all')
            point = 1e3 * double(point(:));
            xValues(end + 1) = point(1); %#ok<AGROW>
            yValues(end + 1) = point(2); %#ok<AGROW>
        end
    end
end
end

function [xLimits, yLimits] = commonLimits(xValues, yValues)
xLimits = paddedRange(xValues);
yLimits = paddedRange(yValues);
end

function limits = paddedRange(values)
minimum = min(values);
maximum = max(values);
span = maximum - minimum;
padding = max(5, 0.08 * max(span, 1));
limits = [minimum - padding, maximum + padding];
end

function restoreAxes(axesHandles, originalNextPlot)
for index = 1:numel(axesHandles)
    if isgraphics(axesHandles(index), 'axes')
        axesHandles(index).NextPlot = char(originalNextPlot(index));
    end
end
end

function invalidInput()
error('duallink5:viz:InvalidCouplingPlotInput', ...
    'Inputs do not satisfy the coupling singularity plot contract.');
end
