function handles = plotTaskSingularitySpace(samples, axesHandles)
axesHandles = validateAxes(axesHandles);
validateSamples(samples);
scale = 1e3;
originalNextPlot = string({axesHandles.NextPlot});
cleanup = onCleanup(@()restoreAxes(axesHandles, originalNextPlot));
set(axesHandles, 'NextPlot', 'add');

theoretical = samples.theoreticalReachableMask;
safe = samples.safeUsableMask;
handles.theoretical = scatter(axesHandles(1), ...
    scale * samples.x(theoretical), scale * samples.y(theoretical), ...
    8, [0.58, 0.79, 0.96], 'filled', ...
    'MarkerFaceAlpha', 0.22, 'MarkerEdgeAlpha', 0.12);
handles.safe = scatter(axesHandles(1), ...
    scale * samples.x(safe), scale * samples.y(safe), ...
    9, [0.22, 0.72, 0.39], 'filled', ...
    'MarkerFaceAlpha', 0.32, 'MarkerEdgeAlpha', 0.18);
handles.typeITheta = plotTaskCurves(axesHandles(1), ...
    samples.curves.typeITheta, [1.00, 0.58, 0.00], '--');
handles.typeIPhi = plotTaskCurves(axesHandles(1), ...
    samples.curves.typeIPhi, [1.00, 0.58, 0.00], ':');
handles.typeIIOuter = plotTaskCurves(axesHandles(1), ...
    samples.curves.typeIIOuter, [0.84, 0.16, 0.16], '--');
handles.typeIIInner = plotTaskCurves(axesHandles(1), ...
    samples.curves.typeIIInner, [0.84, 0.16, 0.16], '-.');
typeIII = collectCurvePoints(samples.curves.typeIII);
handles.typeIII = scatter(axesHandles(1), ...
    scale * typeIII(1, :), scale * typeIII(2, :), ...
    35, [0.49, 0.18, 0.82], 'filled');
if isempty(typeIII)
    typeIIIStatus = 'No Type III locus in sampled range';
else
    typeIIIStatus = '';
end
handles.typeIIIStatus = text(axesHandles(1), 0.02, 0.98, ...
    typeIIIStatus, 'Units', 'normalized', ...
    'VerticalAlignment', 'top', 'Color', [0.49, 0.18, 0.82]);

orientationMask = samples.mechanicallyValidMask & ...
    isfinite(samples.orientationSensitivity) & ...
    samples.orientationSensitivity > 0;
orientationColor = log10(samples.orientationSensitivity(orientationMask));
handles.orientation = scatter(axesHandles(2), ...
    scale * samples.x(orientationMask), ...
    scale * samples.y(orientationMask), 12, orientationColor, 'filled');
colormap(axesHandles(2), turbo(256));
handles.orientationColorbar = colorbar(axesHandles(2));
handles.orientationColorbar.Label.String = ...
    'log_{10} ||\partial\psi/\partialq||_2';

for index = 1:2
    xlabel(axesHandles(index), 'x_G [mm]');
    ylabel(axesHandles(index), 'y_G [mm]');
    axis(axesHandles(index), 'equal');
    grid(axesHandles(index), 'on');
end
title(axesHandles(1), 'Point-G singularity loci and safe workspace');
title(axesHandles(2), 'Shared-link orientation sensitivity');

legendItems = [handles.theoretical, handles.safe, ...
    plot(axesHandles(1), NaN, NaN, 's', 'LineStyle', 'none', ...
        'Color', [1.00, 0.58, 0.00], ...
        'MarkerFaceColor', [1.00, 0.58, 0.00]), ...
    plot(axesHandles(1), NaN, NaN, 's', 'LineStyle', 'none', ...
        'Color', [0.84, 0.16, 0.16], ...
        'MarkerFaceColor', [0.84, 0.16, 0.16]), ...
    scatter(axesHandles(1), NaN, NaN, 35, ...
        [0.49, 0.18, 0.82], 'filled'), ...
    plot(axesHandles(1), NaN, NaN, '--', ...
        'Color', [0.20, 0.22, 0.26], 'LineWidth', 1.2), ...
    plot(axesHandles(1), NaN, NaN, '-', ...
        'Color', [0.20, 0.22, 0.26], 'LineWidth', 2.2)];
handles.legend = legend(axesHandles(1), legendItems, ...
    {'theoretical workspace', 'safe usable workspace', ...
    'Type I', 'Type II', 'Type III', ...
    'theoretical-only curve', 'mechanically adjacent curve'}, ...
    'Location', 'best');
clear cleanup
end

function handles = plotTaskCurves(axesHandle, curves, color, style)
handles = gobjects(1, 2 * numel(curves));
for index = 1:numel(curves)
    points = 1e3 * curves(index).pointG;
    valid = all(isfinite(points), 1);
    theoreticalPoints = points;
    theoreticalPoints(:, ~valid) = NaN;
    handles(2 * index - 1) = plot(axesHandle, ...
        theoreticalPoints(1, :), theoreticalPoints(2, :), ...
        style, 'Color', color, 'LineWidth', 1.2);
    adjacentPoints = theoreticalPoints;
    adjacentPoints(:, ~curves(index).adjacentMechanical) = NaN;
    handles(2 * index) = plot(axesHandle, ...
        adjacentPoints(1, :), adjacentPoints(2, :), '-', ...
        'Color', color, 'LineWidth', 2.2);
end
end

function points = collectCurvePoints(curves)
points = zeros(2, 0);
for index = 1:numel(curves)
    finite = all(isfinite(curves(index).pointG), 1);
    points = [points, curves(index).pointG(:, finite)]; %#ok<AGROW>
end
end

function axesHandles = validateAxes(axesHandles)
if ~isvector(axesHandles) || numel(axesHandles) ~= 2 || ...
        ~all(isgraphics(axesHandles, 'axes'), 'all')
    error('duallink5:viz:InvalidGraphicsHandle', ...
        'axesHandles must contain exactly two live axes.');
end
axesHandles = axesHandles(:).';
if isequal(axesHandles(1), axesHandles(2))
    error('duallink5:viz:InvalidGraphicsHandle', ...
        'axesHandles must contain two distinct live axes.');
end
end

function validateSamples(samples)
required = {'x', 'y', 'orientationSensitivity', ...
    'theoreticalReachableMask', 'mechanicallyValidMask', ...
    'safeUsableMask', 'exact', 'curves'};
if ~isstruct(samples) || ~isscalar(samples) || ...
        ~all(isfield(samples, required))
    invalidPlotInput();
end

shape = size(samples.x);
validCoordinates = isnumeric(samples.x) && isreal(samples.x) && ...
    ismatrix(samples.x) && ~isempty(samples.x) && ...
    isnumeric(samples.y) && isreal(samples.y) && ...
    ismatrix(samples.y) && isequal(size(samples.y), shape);
validOrientation = isnumeric(samples.orientationSensitivity) && ...
    isreal(samples.orientationSensitivity) && ...
    ismatrix(samples.orientationSensitivity) && ...
    isequal(size(samples.orientationSensitivity), shape);
validMasks = islogical(samples.theoreticalReachableMask) && ...
    ismatrix(samples.theoreticalReachableMask) && ...
    isequal(size(samples.theoreticalReachableMask), shape) && ...
    islogical(samples.mechanicallyValidMask) && ...
    ismatrix(samples.mechanicallyValidMask) && ...
    isequal(size(samples.mechanicallyValidMask), shape) && ...
    islogical(samples.safeUsableMask) && ...
    ismatrix(samples.safeUsableMask) && ...
    isequal(size(samples.safeUsableMask), shape);
validNested = isstruct(samples.exact) && isscalar(samples.exact) && ...
    isfield(samples.exact, 'typeIII') && ...
    islogical(samples.exact.typeIII) && ...
    ismatrix(samples.exact.typeIII) && ...
    isequal(size(samples.exact.typeIII), shape) && ...
    isstruct(samples.curves) && isscalar(samples.curves) && ...
    all(isfield(samples.curves, ...
    {'typeITheta', 'typeIPhi', 'typeIIOuter', 'typeIIInner', 'typeIII'}));
if validNested
    names = {'typeITheta', 'typeIPhi', 'typeIIOuter', ...
        'typeIIInner', 'typeIII'};
    validNested = all(cellfun( ...
        @(name)validCurveCollection(samples.curves.(name)), names));
end
theoretical = samples.theoreticalReachableMask;
if ~(validCoordinates && validOrientation && validMasks && validNested) || ...
        any(~isfinite(samples.x(theoretical)), 'all') || ...
        any(~isfinite(samples.y(theoretical)), 'all')
    invalidPlotInput();
end
end

function valid = validCurveCollection(curves)
required = {'theta', 'phi', 'pointG', 'adjacentMechanical'};
valid = isstruct(curves) && all(isfield(curves, required));
if ~valid
    return
end
for index = 1:numel(curves)
    curve = curves(index);
    if ~isnumeric(curve.theta) || ~isreal(curve.theta) || ...
            ~isvector(curve.theta) || ...
            ~isnumeric(curve.phi) || ~isreal(curve.phi) || ...
            ~isvector(curve.phi)
        valid = false;
        return
    end
    pointCount = numel(curve.theta);
    valid = numel(curve.phi) == pointCount && ...
        all(isfinite(curve.theta), 'all') && ...
        all(isfinite(curve.phi), 'all') && ...
        isnumeric(curve.pointG) && isreal(curve.pointG) && ...
        isequal(size(curve.pointG), [2, pointCount]) && ...
        ~any(isinf(curve.pointG), 'all') && ...
        islogical(curve.adjacentMechanical) && ...
        isequal(size(curve.adjacentMechanical), [1, pointCount]);
    if ~valid
        return
    end
end
end

function restoreAxes(axesHandles, originalNextPlot)
for index = 1:numel(axesHandles)
    if isgraphics(axesHandles(index), 'axes')
        axesHandles(index).NextPlot = char(originalNextPlot(index));
    end
end
end

function invalidPlotInput()
error('duallink5:viz:InvalidSingularityPlotInput', ...
    'samples do not satisfy the task singularity plot contract.');
end
