function handles = plotJointSingularitySpace(samples, axesHandles)
axesHandles = validateAxes(axesHandles);
validateSamples(samples);
thetaDegrees = rad2deg(samples.thetaGrid(:, 1));
phiDegrees = rad2deg(samples.phiGrid(1, :));
thetaEdges = cellEdges(thetaDegrees);
phiEdges = cellEdges(phiDegrees);
[thetaEdgeGrid, phiEdgeGrid] = meshgrid(thetaEdges, phiEdges);
originalNextPlot = string({axesHandles.NextPlot});
cleanup = onCleanup(@()restoreAxes(axesHandles, originalNextPlot));
set(axesHandles, 'NextPlot', 'add');

conditionData = log10(samples.conditionNumber.task);
conditionData(~samples.theoreticalReachableMask | ...
    ~isfinite(conditionData)) = NaN;
handles.conditionImage = plotCellMap(axesHandles(1), ...
    thetaEdgeGrid, phiEdgeGrid, conditionData.');
set(axesHandles(1), 'YDir', 'normal');
colormap(axesHandles(1), turbo(256));
clim(axesHandles(1), conditionColorLimits(conditionData));
handles.conditionColorbar = colorbar(axesHandles(1));
handles.conditionColorbar.Label.String = 'log_{10} \kappa(J_G)';

nearMask = samples.near.any & samples.theoreticalReachableMask;
handles.nearBand = scatter(axesHandles(1), ...
    rad2deg(samples.thetaGrid(nearMask)), ...
    rad2deg(samples.phiGrid(nearMask)), 12, ...
    [0.49, 0.18, 0.82], 'filled', ...
    'MarkerFaceAlpha', 0.22, 'MarkerEdgeAlpha', 0.22);
handles.typeITheta = plotJointCurves(axesHandles(1), ...
    samples.curves.typeITheta, [1.00, 0.58, 0.00], '-', 1.8);
handles.typeIPhi = plotJointCurves(axesHandles(1), ...
    samples.curves.typeIPhi, [1.00, 0.58, 0.00], ':', 1.8);
handles.typeIIOuter = plotJointCurves(axesHandles(1), ...
    samples.curves.typeIIOuter, [0.84, 0.16, 0.16], '--', 2.0);
handles.typeIIInner = plotJointCurves(axesHandles(1), ...
    samples.curves.typeIIInner, [0.84, 0.16, 0.16], '-.', 2.0);
referenceDegrees = rad2deg(samples.metadata.referenceQ);
handles.reference = plot(axesHandles(1), referenceDegrees(1), ...
    referenceDegrees(2), 'wo', 'MarkerEdgeColor', [0.07, 0.09, 0.12], ...
    'MarkerFaceColor', 'w', 'LineWidth', 1.4, 'MarkerSize', 7);

category = buildCategoryMap(samples);
handles.categoryImage = plotCellMap(axesHandles(2), ...
    thetaEdgeGrid, phiEdgeGrid, category.');
set(axesHandles(2), 'YDir', 'normal');
colormap(axesHandles(2), [ ...
    0.90, 0.91, 0.93; 0.73, 0.90, 0.98; ...
    0.29, 0.35, 0.43; 0.66, 0.33, 0.85; ...
    0.96, 0.68, 0.18; 0.31, 0.78, 0.47]);
clim(axesHandles(2), [-0.5, 5.5]);
handles.categoryColorbar = colorbar(axesHandles(2));
handles.categoryColorbar.Ticks = 0:5;
handles.categoryColorbar.TickLabels = { ...
    'unreachable', 'theoretical', 'collision', ...
    'topology', 'near singular', 'safe usable'};
plot(axesHandles(2), referenceDegrees(1), referenceDegrees(2), ...
    'ko', 'MarkerFaceColor', 'w', 'LineWidth', 1.2);

for index = 1:2
    xlabel(axesHandles(index), '\theta [deg]');
    ylabel(axesHandles(index), '\phi [deg]');
    xlim(axesHandles(index), thetaEdges([1, end]));
    ylim(axesHandles(index), phiEdges([1, end]));
    grid(axesHandles(index), 'on');
end
title(axesHandles(1), 'Conditioning and singular curves');
title(axesHandles(2), 'Configuration validity and safe domain');

legendItems = [ ...
    plot(axesHandles(1), NaN, NaN, '-', ...
        'Color', [1.00, 0.58, 0.00], 'LineWidth', 1.8), ...
    plot(axesHandles(1), NaN, NaN, '--', ...
        'Color', [0.84, 0.16, 0.16], 'LineWidth', 2.0), ...
    plot(axesHandles(1), NaN, NaN, 's', ...
        'Color', [0.49, 0.18, 0.82], ...
        'MarkerFaceColor', [0.49, 0.18, 0.82]), ...
    handles.reference];
handles.legend = legend(axesHandles(1), legendItems, ...
    {'Type I', 'Type II', 'near singular', 'reference'}, ...
    'Location', 'best');
clear cleanup
end

function category = buildCategoryMap(samples)
category = zeros(size(samples.thetaGrid));
reachable = samples.theoreticalReachableMask;
category(reachable) = 1;
collision = reachable & (contains(samples.reasonMap, "COLLISION") | ...
    contains(samples.reasonMap, "CLEARANCE"));
category(collision) = 2;
topology = reachable & ...
    samples.reasonMap == "ASSEMBLY_TOPOLOGY_MISMATCH";
category(topology) = 3;
category(samples.mechanicallyValidMask & samples.near.any) = 4;
category(samples.safeUsableMask) = 5;
category(~reachable | ...
    samples.reasonMap == "JOINT_LIMIT_VIOLATION") = 0;
end

function limits = paddedLimits(values)
limits = [values(1), values(end)];
if limits(1) == limits(2)
    halfWidth = max(1, 0.01 * abs(limits(1)));
    limits = limits + [-halfWidth, halfWidth];
end
end

function edges = cellEdges(values)
centers = double(values(:).');
if isscalar(centers)
    edges = paddedLimits(centers);
    return
end
halfSpacing = 0.5 * diff(centers);
edges = [centers(1) - halfSpacing(1), ...
    centers(1:end - 1) + halfSpacing, ...
    centers(end) + halfSpacing(end)];
end

function handle = plotCellMap(axesHandle, xEdges, yEdges, faceData)
rowIndices = [1:size(faceData, 1), size(faceData, 1)];
columnIndices = [1:size(faceData, 2), size(faceData, 2)];
paddedData = faceData(rowIndices, columnIndices);
handle = surface(axesHandle, xEdges, yEdges, ...
    zeros(size(paddedData)), paddedData, ...
    'FaceColor', 'flat', 'EdgeColor', 'none');
view(axesHandle, 2);
end

function limits = conditionColorLimits(conditionData)
finiteValues = conditionData(isfinite(conditionData));
limits = [0, 1];
if ~isempty(finiteValues)
    minimum = min(finiteValues, [], 'all');
    maximum = max(finiteValues, [], 'all');
    if minimum < maximum
        limits = [minimum, maximum];
    else
        limits = [0, max(1, maximum)];
    end
end
end

function handles = plotJointCurves(axesHandle, curves, color, style, width)
handles = gobjects(0);
for index = 1:numel(curves)
    handles(end + 1) = plot(axesHandle, ...
        rad2deg(curves(index).theta), ...
        rad2deg(curves(index).phi), style, ...
        'Color', color, 'LineWidth', width); %#ok<AGROW>
end
end

function axesHandles = validateAxes(axesHandles)
if ~isvector(axesHandles) || numel(axesHandles) ~= 2 || ...
        ~all(isgraphics(axesHandles, 'axes'), 'all')
    error('duallink5:viz:InvalidGraphicsHandle', ...
        'axesHandles must contain exactly two live axes.');
end
axesHandles = axesHandles(:).';
if isequal(axesHandles(1), axesHandles(2))
    error('duallink5:viz:InvalidGraphicsHandle', ...
        'axesHandles must contain two distinct live axes.');
end
end

function validateSamples(samples)
required = {'thetaGrid', 'phiGrid', 'theoreticalReachableMask', ...
    'mechanicallyValidMask', 'safeUsableMask', 'reasonMap', ...
    'classificationMap', 'conditionNumber', 'near', 'curves', 'metadata'};
if ~isstruct(samples) || ~isscalar(samples) || ...
        ~all(isfield(samples, required))
    invalidPlotInput();
end

shape = size(samples.thetaGrid);
validGrids = isnumeric(samples.thetaGrid) && ...
    isreal(samples.thetaGrid) && ismatrix(samples.thetaGrid) && ...
    ~isempty(samples.thetaGrid) && ...
    all(isfinite(samples.thetaGrid), 'all') && ...
    isnumeric(samples.phiGrid) && isreal(samples.phiGrid) && ...
    ismatrix(samples.phiGrid) && ~isempty(samples.phiGrid) && ...
    all(isfinite(samples.phiGrid), 'all') && ...
    isequal(size(samples.phiGrid), shape);
if validGrids
    validGrids = validGridStructure( ...
        samples.thetaGrid, samples.phiGrid);
end
validMasks = islogical(samples.theoreticalReachableMask) && ...
    isequal(size(samples.theoreticalReachableMask), shape) && ...
    islogical(samples.mechanicallyValidMask) && ...
    isequal(size(samples.mechanicallyValidMask), shape) && ...
    islogical(samples.safeUsableMask) && ...
    isequal(size(samples.safeUsableMask), shape);
validMaps = isstring(samples.reasonMap) && ...
    isequal(size(samples.reasonMap), shape) && ...
    ~any(ismissing(samples.reasonMap), 'all') && ...
    isstring(samples.classificationMap) && ...
    isequal(size(samples.classificationMap), shape) && ...
    ~any(ismissing(samples.classificationMap), 'all');
validCondition = isstruct(samples.conditionNumber) && ...
    isscalar(samples.conditionNumber) && ...
    isfield(samples.conditionNumber, 'task') && ...
    isnumeric(samples.conditionNumber.task) && ...
    isreal(samples.conditionNumber.task) && ...
    isequal(size(samples.conditionNumber.task), shape) && ...
    all(isnan(samples.conditionNumber.task) | ...
    samples.conditionNumber.task >= 1, 'all');
validNear = isstruct(samples.near) && isscalar(samples.near) && ...
    isfield(samples.near, 'any') && islogical(samples.near.any) && ...
    isequal(size(samples.near.any), shape);
validCurves = isstruct(samples.curves) && isscalar(samples.curves) && ...
    all(isfield(samples.curves, ...
    {'typeITheta', 'typeIPhi', 'typeIIOuter', 'typeIIInner'}));
if validCurves
    names = {'typeITheta', 'typeIPhi', 'typeIIOuter', 'typeIIInner'};
    validCurves = all(cellfun( ...
        @(name)validJointCurveCollection(samples.curves.(name)), names));
end
validMetadata = isstruct(samples.metadata) && ...
    isscalar(samples.metadata) && ...
    isfield(samples.metadata, 'referenceQ') && ...
    isnumeric(samples.metadata.referenceQ) && ...
    isreal(samples.metadata.referenceQ) && ...
    isequal(size(samples.metadata.referenceQ), [1, 2]) && ...
    all(isfinite(samples.metadata.referenceQ), 'all');
validRelationships = validMasks && validMaps && validNear && ...
    validSampleRelationships(samples);
if ~(validGrids && validMasks && validMaps && validCondition && ...
        validNear && validCurves && validMetadata && validRelationships)
    invalidPlotInput();
end
end

function valid = validGridStructure(thetaGrid, phiGrid)
theta = thetaGrid(:, 1);
phi = phiGrid(1, :);
valid = all(diff(double(theta)) > 0) && ...
    all(diff(double(phi)) > 0) && ...
    all(thetaGrid == theta, 'all') && ...
    all(phiGrid == phi, 'all');
end

function valid = validSampleRelationships(samples)
theoretical = samples.theoreticalReachableMask;
mechanical = samples.mechanicallyValidMask;
safe = samples.safeUsableMask;
near = samples.near.any;
reason = samples.reasonMap;
blockedReason = contains(reason, "COLLISION") | ...
    contains(reason, "CLEARANCE") | ...
    reason == "ASSEMBLY_TOPOLOGY_MISMATCH" | ...
    reason == "JOINT_LIMIT_VIOLATION";
nearReason = reason == "NEAR_SINGULAR";
nearMechanical = mechanical & near;
regularMechanical = mechanical & ~near;
valid = ~any(safe & ~mechanical, 'all') && ...
    ~any(mechanical & ~theoretical, 'all') && ...
    ~any(blockedReason & (mechanical | safe), 'all') && ...
    all(~nearReason | (mechanical & near & ~safe), 'all') && ...
    all(~nearMechanical | (nearReason & ~safe), 'all') && ...
    all(~regularMechanical | (reason == "OK" & safe), 'all');
end

function valid = validJointCurveCollection(curves)
required = {'theta', 'phi', 'pointG', 'adjacentMechanical'};
valid = isstruct(curves) && all(isfield(curves, required));
if ~valid
    return
end
for index = 1:numel(curves)
    curve = curves(index);
    valid = isnumeric(curve.theta) && isreal(curve.theta) && ...
        isvector(curve.theta) && all(isfinite(curve.theta), 'all') && ...
        isnumeric(curve.phi) && isreal(curve.phi) && ...
        isvector(curve.phi) && all(isfinite(curve.phi), 'all') && ...
        numel(curve.theta) == numel(curve.phi) && ...
        isnumeric(curve.pointG) && isreal(curve.pointG) && ...
        isequal(size(curve.pointG), [2, numel(curve.theta)]) && ...
        islogical(curve.adjacentMechanical) && ...
        isvector(curve.adjacentMechanical) && ...
        numel(curve.adjacentMechanical) == numel(curve.theta);
    if ~valid
        return
    end
end
end

function restoreAxes(axesHandles, originalNextPlot)
for index = 1:numel(axesHandles)
    if isgraphics(axesHandles(index), 'axes')
        axesHandles(index).NextPlot = char(originalNextPlot(index));
    end
end
end

function invalidPlotInput()
error('duallink5:viz:InvalidSingularityPlotInput', ...
    'samples do not satisfy the joint singularity plot contract.');
end
