analyzeCouplingSingularityExample();

function analyzeCouplingSingularityExample()
originalPath = path;
pathCleanup = onCleanup(@()path(originalPath));
scriptDir = fileparts(mfilename('fullpath'));
projectRoot = fileparts(scriptDir);
run(fullfile(projectRoot, 'startup.m'));

geometry = duallink5.model.defaultGeometry();
grid.theta = deg2rad(0:1:180);
grid.phi = deg2rad(-30:1:30);
options = struct( ...
    'collisionProfile', "centerline", ...
    'topologyProfile', "reference");

analysisFigure = [];
try
    timer = tic;
    samples = duallink5.singularity.sampleCouplingSpace( ...
        grid, geometry, options);
    samplingSeconds = toc(timer);

    analysisFigure = figure( ...
        'Name', 'DualLink5 doublet coupling singularity analysis', ...
        'NumberTitle', 'off', ...
        'Position', [80, 80, 1600, 820]);
    axesHandles = gobjects(1, 5);
    axesHandles(1) = axes(analysisFigure, ...
        'Position', [0.055, 0.10, 0.39, 0.82]);
    axesHandles(2) = axes(analysisFigure, ...
        'Position', [0.50, 0.55, 0.20, 0.36]);
    axesHandles(3) = axes(analysisFigure, ...
        'Position', [0.76, 0.69, 0.21, 0.25]);
    axesHandles(4) = axes(analysisFigure, ...
        'Position', [0.76, 0.385, 0.21, 0.25]);
    axesHandles(5) = axes(analysisFigure, ...
        'Position', [0.76, 0.08, 0.21, 0.25]);
    handles = duallink5.viz.plotCouplingSingularitySpace( ...
        samples, axesHandles, struct('geometry', geometry));

    summary = couplingSummary(samples);
    referenceQ = geometry.analysis.referenceQ;
    reference = duallink5.singularity.evaluateCoupling( ...
        referenceQ, geometry, options);
    analysisFigure.UserData = struct( ...
        'handles', handles, ...
        'axes', axesHandles, ...
        'samples', samples, ...
        'summary', summary, ...
        'reference', reference, ...
        'samplingSeconds', samplingSeconds);
    drawnow;

    printSummary(summary, reference, samplingSeconds);
catch exception
    if isgraphics(analysisFigure, 'figure')
        close(analysisFigure);
    end
    rethrow(exception);
end
clear pathCleanup
end

function summary = couplingSummary(samples)
summary = struct( ...
    'theoreticalCount', nnz(samples.theoreticalReachableMask), ...
    'mechanicalCount', nnz(samples.mechanicallyValidMask), ...
    'exactCount', nnz(samples.exactCouplingSingular), ...
    'nearCount', nnz(samples.nearCouplingSingular), ...
    'warningCount', nnz(samples.engineeringWarning), ...
    'safeCount', nnz(samples.safeUsableMask));
end

function printSummary(summary, reference, samplingSeconds)
qDegrees = rad2deg(reference.metadata.qLower);
pointGMillimetres = 1e3 * reference.kinematics.points.G;
fprintf('DualLink5 coupling sampling: %.3f s\n', samplingSeconds);
fprintf(['Theoretically reachable/mechanically valid/exact/near/', ...
    'engineering-warning/safe samples: ', ...
    '%d / %d / %d / %d / %d / %d\n'], ...
    summary.theoreticalCount, summary.mechanicalCount, ...
    summary.exactCount, summary.nearCount, summary.warningCount, ...
    summary.safeCount);
fprintf('Reference q [deg]: theta %.3f, phi %.3f\n', ...
    qDegrees(1), qDegrees(2));
fprintf('Reference G [mm]: x %.3f, y %.3f\n', ...
    pointGMillimetres(1), pointGMillimetres(2));
fprintf(['Reference coupling: margin %.6g, sigma_min %.6g, ', ...
    'condition %.6g, status %s, assembly %s\n'], ...
    reference.coupling.margin, reference.coupling.sigmaMin, ...
    reference.coupling.conditionNumber, char(reference.statusCode), ...
    char(reference.assemblyStatusCode));
end
