function samples = sampleCouplingSpace(grid, geometry, options)
%SAMPLECOUPLINGSPACE Sample passive-doublet coupling over a joint grid.
if nargin < 3
    options = struct();
end
geometry = duallink5.model.validateGeometry(geometry);
options = normalizeCouplingOptions(options, geometry);
[theta, phi] = validateGrid(grid);
[thetaGrid, phiGrid] = ndgrid(theta, phi);
samples = allocateSamples(thetaGrid, phiGrid);

reference = canonicalReference(options, geometry);
options.couplingReference = reference;
for index = 1:numel(thetaGrid)
    result = duallink5.singularity.evaluateCoupling( ...
        [thetaGrid(index), phiGrid(index)], geometry, options);
    samples = copyResult(samples, result, index);
end

samples.metadata = makeMetadata( ...
    geometry, options, reference, size(thetaGrid));
end

function reference = canonicalReference(options, geometry)
supplied = options.couplingReference;
buildOptions = options;
buildOptions.couplingReference = [];
reference = prepareCouplingReference(buildOptions, geometry);
if ~isempty(supplied) && ~semanticallyEquivalent(supplied, reference)
    error('duallink5:singularity:InvalidCouplingOptions', ...
        'couplingReference does not match the current reference semantics.');
end
end

function equivalent = semanticallyEquivalent(supplied, canonical)
fingerprint = supplied.geometryFingerprint;
equivalent = isequal(supplied.q, canonical.q) && ...
    supplied.passiveOrientationSign == ...
    canonical.passiveOrientationSign && ...
    isequal(supplied.topology, canonical.topology) && ...
    isequal(supplied.geometryVersion, canonical.geometryVersion) && ...
    (isempty(fieldnames(fingerprint)) || ...
    isequal(fingerprint, canonical.geometryFingerprint));
end

function [theta, phi] = validateGrid(grid)
if ~isstruct(grid) || ~isscalar(grid) || ...
        ~isfield(grid, 'theta') || ~isfield(grid, 'phi') || ...
        ~isIncreasingFiniteVector(grid.theta) || ...
        ~isIncreasingFiniteVector(grid.phi)
    error('duallink5:singularity:InvalidCouplingGrid', ...
        ['grid.theta and grid.phi must be nonempty, finite, real, ', ...
        'strictly increasing numeric vectors.']);
end
theta = full(double(grid.theta(:).'));
phi = full(double(grid.phi(:).'));
end

function valid = isIncreasingFiniteVector(value)
valid = isnumeric(value) && isreal(value) && isvector(value) && ...
    ~isempty(value) && all(isfinite(value), 'all') && ...
    all(diff(double(value(:))) > 0);
end

function samples = allocateSamples(thetaGrid, phiGrid)
shape = size(thetaGrid);
samples.thetaGrid = thetaGrid;
samples.phiGrid = phiGrid;
samples.x = nan(shape);
samples.y = nan(shape);
samples.couplingMargin = nan(shape);
samples.sigmaMin = nan(shape);
samples.conditionNumber = nan(shape);
samples.constraintMatrix = nan([2, 2, shape]);
samples.actuationMatrix = nan([2, 2, shape]);
samples.taskJacobian = nan([2, 2, shape]);
samples.passiveDirection = nan([2, shape]);
samples.theoreticalReachableMask = false(shape);
samples.mechanicallyValidMask = false(shape);
samples.exactCouplingSingular = false(shape);
samples.nearCouplingSingular = false(shape);
samples.engineeringWarning = false(shape);
samples.safeUsableMask = false(shape);
samples.reasonMap = strings(shape);
samples.assemblyStatusMap = strings(shape);
samples.passiveOrientationSign = nan(shape);
samples.lowerClosureSingular = false(shape);
end

function samples = copyResult(samples, result, index)
samples.theoreticalReachableMask(index) = ...
    result.theoreticallyReachable;
samples.mechanicallyValidMask(index) = result.mechanicallyValid;
samples.exactCouplingSingular(index) = ...
    result.exactCouplingSingular;
samples.nearCouplingSingular(index) = ...
    result.nearCouplingSingular;
samples.engineeringWarning(index) = result.engineeringWarning;
samples.reasonMap(index) = result.statusCode;
samples.assemblyStatusMap(index) = result.assemblyStatusCode;
samples.lowerClosureSingular(index) = ...
    result.statusCode == "LOWER_CLOSURE_SINGULAR";
samples.safeUsableMask(index) = result.mechanicallyValid && ...
    ~result.exactCouplingSingular && ...
    ~result.nearCouplingSingular && ~result.engineeringWarning;

samples.couplingMargin(index) = result.coupling.margin;
samples.sigmaMin(index) = result.coupling.sigmaMin;
samples.conditionNumber(index) = result.coupling.conditionNumber;
[row, column] = ind2sub(size(samples.thetaGrid), index);
samples.constraintMatrix(:, :, row, column) = ...
    result.coupling.constraintMatrix;
samples.actuationMatrix(:, :, row, column) = ...
    result.coupling.actuationMatrix;
samples.taskJacobian(:, :, row, column) = ...
    result.coupling.taskJacobian;
samples.passiveDirection(:, row, column) = ...
    result.coupling.passiveDirection;
samples.passiveOrientationSign(index) = ...
    double(result.kinematics.quality.passiveOrientationSign);
if result.theoreticallyReachable
    samples.x(index) = result.kinematics.points.G(1);
    samples.y(index) = result.kinematics.points.G(2);
end
end

function metadata = makeMetadata(geometry, options, reference, gridShape)
metadata = struct( ...
    'units', geometry.units, ...
    'storageLengthUnit', "m", ...
    'storageAngleUnit', "rad", ...
    'displayLengthUnit', "mm", ...
    'displayAngleUnit', "deg", ...
    'couplingWarningAngle', geometry.analysis.couplingWarningAngle, ...
    'exactThreshold', options.exactThreshold, ...
    'nearMetricThreshold', options.nearMetricThreshold, ...
    'nearConditionThreshold', options.nearConditionThreshold, ...
    'referenceQ', reference.q, ...
    'referencePassiveOrientationSign', ...
    reference.passiveOrientationSign, ...
    'referenceSign', reference.passiveOrientationSign, ...
    'couplingReference', reference, ...
    'branchId', options.lowerBranchId, ...
    'lowerBranchId', options.lowerBranchId, ...
    'lowerBranchMode', options.lowerBranchMode, ...
    'collisionProfile', options.collisionProfile, ...
    'topologyProfile', options.topologyProfile, ...
    'geometryVersion', string(geometry.version), ...
    'gridShape', gridShape, ...
    'referenceBuildCount', 1);
end
