function comparison = compareAssemblyTopologyToReference( ...
        candidateAssembly, reference)
if ~isstruct(reference) || ~isscalar(reference) || ...
        ~isfield(reference, 'signature') || ...
        ~isstring(reference.signature) || ...
        ~ismatrix(reference.signature) || ...
        size(reference.signature, 2) ~= 2 || ...
        any(ismissing(reference.signature), 'all') || ...
        ~isfield(reference, 'lengthTolerance') || ...
        ~isnumeric(reference.lengthTolerance) || ...
        ~isreal(reference.lengthTolerance) || ...
        ~isscalar(reference.lengthTolerance) || ...
        ~isfinite(reference.lengthTolerance) || ...
        reference.lengthTolerance <= 0
    invalidTopology();
end

try
    candidateSignature = assemblyTopologySignature( ...
        candidateAssembly, reference.lengthTolerance);
catch exception
    if strcmp(exception.identifier, ...
            'duallink5:validation:InvalidAssemblyTopology')
        rethrow(exception)
    end
    invalidTopology();
end

referenceSignature = reference.signature;
comparison.candidateSignature = candidateSignature;
comparison.referenceSignature = referenceSignature;
comparison.addedCrossings = setdiff( ...
    candidateSignature, referenceSignature, 'rows');
comparison.removedCrossings = setdiff( ...
    referenceSignature, candidateSignature, 'rows');
comparison.compatible = isempty(comparison.addedCrossings) && ...
    isempty(comparison.removedCrossings);
if comparison.compatible
    comparison.statusCode = "OK";
else
    comparison.statusCode = "ASSEMBLY_TOPOLOGY_MISMATCH";
end
end

function invalidTopology()
error('duallink5:validation:InvalidAssemblyTopology', ...
    'Assemblies must contain finite complete assembly points.');
end
