function comparison = compareAssemblyTopology( ...
        candidateAssembly, referenceAssembly, geometry)
geometry = duallink5.model.validateGeometry(geometry);
reference = duallink5.validation.prepareAssemblyTopologyReference( ...
    referenceAssembly, geometry.tolerance.length);
comparison = duallink5.validation.compareAssemblyTopologyToReference( ...
    candidateAssembly, reference);
end
