function [safe, details] = isCollisionFree(pose, geometry, profile)
geometry = duallink5.model.validateGeometry(geometry);
try
    profile = string(profile);
catch
    invalidCollisionProfile();
end
if ~isscalar(profile) || ismissing(profile) || ...
        ~ismember(profile, ["centerline", "physicalClearance"])
    invalidCollisionProfile();
end

details.clearanceModelApplied = profile == "physicalClearance";
if details.clearanceModelApplied
    validatePhysicalGeometry(geometry.collision);
end

p = pose.points;
segments = [ ...
    makeSegment("link1", p.A, p.E, "A", "E"), ...
    makeSegment("link2", p.B, p.C, "B", "C"), ...
    makeSegment("link3", p.C, p.D, "C", "D"), ...
    makeSegment("link4", p.E, p.D, "E", "D"), ...
    makeSegment("link5", p.A, p.B, "A", "B")];

pairBuffer = strings(nchoosek(numel(segments), 2), 2);
pairCount = 0;
safe = true;

for first = 1:numel(segments) - 1
    for second = first + 1:numel(segments)
        if shareTopologicalJoint(segments(first), segments(second))
            continue
        end
        if isExempt(segments(first).name, segments(second).name, ...
                geometry.collision.exemptPairs)
            continue
        end

        if profile == "centerline"
            collision = segmentsIntersect( ...
                segments(first).p1, segments(first).p2, ...
                segments(second).p1, segments(second).p2, ...
                geometry.tolerance.length);
        else
            firstName = char(segments(first).name);
            secondName = char(segments(second).name);
            required = geometry.collision.radius.(firstName) + ...
                geometry.collision.radius.(secondName) + ...
                geometry.collision.clearance;
            planarDistance = segmentDistance( ...
                segments(first).p1, segments(first).p2, ...
                segments(second).p1, segments(second).p2, ...
                geometry.tolerance.length);
            layerDistance = ...
                geometry.collision.layerOffset.(firstName) - ...
                geometry.collision.layerOffset.(secondName);
            actual = hypot(planarDistance, layerDistance);
            collision = actual < required;
        end

        if collision
            safe = false;
            pairCount = pairCount + 1;
            pairBuffer(pairCount, :) = ...
                [segments(first).name, segments(second).name];
        end
    end
end

details.collidingPairs = pairBuffer(1:pairCount, :);
end

function value = makeSegment(name, p1, p2, joint1, joint2)
value = struct( ...
    'name', string(name), ...
    'p1', p1(:), ...
    'p2', p2(:), ...
    'joints', [string(joint1), string(joint2)]);
end

function tf = shareTopologicalJoint(first, second)
tf = any(first.joints == second.joints(1)) || ...
    any(first.joints == second.joints(2));
end

function tf = isExempt(first, second, exemptPairs)
tf = any( ...
    (exemptPairs(:, 1) == first & exemptPairs(:, 2) == second) | ...
    (exemptPairs(:, 1) == second & exemptPairs(:, 2) == first));
end

function validatePhysicalGeometry(collision)
names = {'link1', 'link2', 'link3', 'link4', 'link5'};
for index = 1:numel(names)
    name = names{index};
    validRadius = isfield(collision.radius, name) && ...
        isscalar(collision.radius.(name)) && ...
        isnumeric(collision.radius.(name)) && ...
        isreal(collision.radius.(name)) && ...
        isfinite(collision.radius.(name)) && ...
        collision.radius.(name) >= 0;
    validLayer = isfield(collision.layerOffset, name) && ...
        isscalar(collision.layerOffset.(name)) && ...
        isnumeric(collision.layerOffset.(name)) && ...
        isreal(collision.layerOffset.(name)) && ...
        isfinite(collision.layerOffset.(name));
    if ~validRadius || ~validLayer
        error('duallink5:validation:MissingClearanceGeometry', ...
            ['physicalClearance requires nonnegative link radii ', ...
             'and finite layer offsets for link1 through link5.']);
    end
end
end

function invalidCollisionProfile()
error('duallink5:validation:InvalidCollisionProfile', ...
    'profile must be centerline or physicalClearance.');
end
