function [safe, details] = isCollisionFree(pose, geometry, profile)
geometry = duallink5.model.validateGeometry(geometry);
profile = duallink5.validation.validateCollisionConfiguration( ...
    profile, geometry.collision, false);

details.clearanceModelApplied = profile == "physicalClearance";
validateFiveBarPose(pose, "collision");
p = pose.points;
segments = [ ...
    makeSegment("link1", p.A, p.E, "A", "E"), ...
    makeSegment("link2", p.B, p.C, "B", "C"), ...
    makeSegment("link3", p.C, p.D, "C", "D"), ...
    makeSegment("link4", p.E, p.D, "E", "D"), ...
    makeSegment("link5", p.A, p.B, "A", "B")];

pairBuffer = strings(nchoosek(numel(segments), 2), 2);
pairCount = 0;
safe = true;

for first = 1:numel(segments) - 1
    for second = first + 1:numel(segments)
        if shareTopologicalJoint(segments(first), segments(second))
            continue
        end
        if isExempt(segments(first).name, segments(second).name, ...
                geometry.collision.exemptPairs)
            continue
        end

        if profile == "centerline"
            collision = segmentsIntersect( ...
                segments(first).p1, segments(first).p2, ...
                segments(second).p1, segments(second).p2, ...
                geometry.tolerance.length);
        else
            firstName = char(segments(first).name);
            secondName = char(segments(second).name);
            required = geometry.collision.radius.(firstName) + ...
                geometry.collision.radius.(secondName) + ...
                geometry.collision.clearance;
            planarDistance = segmentDistance( ...
                segments(first).p1, segments(first).p2, ...
                segments(second).p1, segments(second).p2, ...
                geometry.tolerance.length);
            layerDistance = ...
                geometry.collision.layerOffset.(firstName) - ...
                geometry.collision.layerOffset.(secondName);
            actual = hypot(planarDistance, layerDistance);
            collision = actual < required;
        end

        if collision
            safe = false;
            pairCount = pairCount + 1;
            pairBuffer(pairCount, :) = ...
                [segments(first).name, segments(second).name];
        end
    end
end

details.collidingPairs = pairBuffer(1:pairCount, :);
end

function value = makeSegment(name, p1, p2, joint1, joint2)
value = struct( ...
    'name', string(name), ...
    'p1', p1(:), ...
    'p2', p2(:), ...
    'joints', [string(joint1), string(joint2)]);
end

function tf = shareTopologicalJoint(first, second)
tf = any(first.joints == second.joints(1)) || ...
    any(first.joints == second.joints(2));
end

function tf = isExempt(first, second, exemptPairs)
tf = any( ...
    (exemptPairs(:, 1) == first & exemptPairs(:, 2) == second) | ...
    (exemptPairs(:, 1) == second & exemptPairs(:, 2) == first));
end
