function signature = assemblyTopologySignature(assembly, tolerance)
segments = buildSegments(assembly);
pairs = strings(nchoosek(numel(segments), 2), 2);
pairCount = 0;

for first = 1:numel(segments) - 1
    for second = first + 1:numel(segments)
        if sharesJoint(segments(first), segments(second))
            continue
        end
        if properInteriorIntersection( ...
                segments(first), segments(second), tolerance)
            pairCount = pairCount + 1;
            pairs(pairCount, :) = sort( ...
                [segments(first).name, segments(second).name]);
        end
    end
end

signature = sortrows(pairs(1:pairCount, :), [1, 2]);
end

function segments = buildSegments(assembly)
if ~isstruct(assembly) || ~isscalar(assembly) || ...
        ~all(isfield(assembly, {'lower', 'upper'}))
    invalidAssembly();
end

mainNames = {'A', 'B', 'C', 'D', 'E'};
parallelNames = {'Palpha1', 'Palpha2', 'Palpha3', 'Palpha4', ...
    'Pbeta1', 'Pbeta2', 'Pbeta3', 'Pbeta4'};
lower = validatePoints(assembly.lower, [mainNames, parallelNames]);
upper = validatePoints(assembly.upper, mainNames);

segments = [ ...
    makeSegment("lower.link5", lower.A, lower.B, ...
        "lower.A", "lower.B"), ...
    makeSegment("lower.link1", lower.A, lower.E, ...
        "lower.A", "shared.E"), ...
    makeSegment("lower.link2", lower.B, lower.C, ...
        "lower.B", "lower.C"), ...
    makeSegment("lower.link3", lower.C, lower.D, ...
        "lower.C", "shared.D"), ...
    makeSegment("shared.link4", lower.E, lower.D, ...
        "shared.E", "shared.D"), ...
    makeSegment("upper.link5", upper.A, upper.B, ...
        "upper.A", "upper.B"), ...
    makeSegment("upper.link1", upper.A, upper.E, ...
        "upper.A", "shared.D"), ...
    makeSegment("upper.link2", upper.B, upper.C, ...
        "upper.B", "upper.C"), ...
    makeSegment("upper.link3", upper.C, upper.D, ...
        "upper.C", "shared.E"), ...
    makeSegment("alpha.12", lower.Palpha1, lower.Palpha2, ...
        "alpha.1", "alpha.2"), ...
    makeSegment("alpha.23", lower.Palpha2, lower.Palpha3, ...
        "alpha.2", "alpha.3"), ...
    makeSegment("alpha.34", lower.Palpha3, lower.Palpha4, ...
        "alpha.3", "alpha.4"), ...
    makeSegment("alpha.41", lower.Palpha4, lower.Palpha1, ...
        "alpha.4", "alpha.1"), ...
    makeSegment("beta.12", lower.Pbeta1, lower.Pbeta2, ...
        "beta.1", "beta.2"), ...
    makeSegment("beta.23", lower.Pbeta2, lower.Pbeta3, ...
        "beta.2", "beta.3"), ...
    makeSegment("beta.34", lower.Pbeta3, lower.Pbeta4, ...
        "beta.3", "beta.4"), ...
    makeSegment("beta.41", lower.Pbeta4, lower.Pbeta1, ...
        "beta.4", "beta.1")];
end

function points = validatePoints(pose, names)
if ~isstruct(pose) || ~isscalar(pose) || ...
        ~isfield(pose, 'points') || ...
        ~isstruct(pose.points) || ~isscalar(pose.points) || ...
        ~all(isfield(pose.points, names))
    invalidAssembly();
end

points = struct();
for index = 1:numel(names)
    name = names{index};
    points.(name) = validatePoint(pose.points.(name));
end
end

function point = validatePoint(point)
if ~isnumeric(point) || ~isreal(point) || ...
        ~isvector(point) || numel(point) ~= 2 || ...
        any(~isfinite(point), 'all')
    invalidAssembly();
end
point = full(double(point(:)));
end

function segment = makeSegment(name, p1, p2, joint1, joint2)
segment = struct( ...
    'name', name, ...
    'p1', p1, ...
    'p2', p2, ...
    'joints', [joint1, joint2]);
end

function tf = sharesJoint(first, second)
tf = any(first.joints == second.joints(1)) || ...
    any(first.joints == second.joints(2));
end

function intersects = properInteriorIntersection(first, second, tolerance)
r = first.p2 - first.p1;
s = second.p2 - second.p1;
denominator = cross2(r, s);
orientationTolerance = tolerance * ...
    max([norm(r), norm(s), tolerance]);
if abs(denominator) <= orientationTolerance
    intersects = false;
    return
end

t = cross2(second.p1 - first.p1, s) / denominator;
u = cross2(second.p1 - first.p1, r) / denominator;
tTolerance = tolerance / max(norm(r), tolerance);
uTolerance = tolerance / max(norm(s), tolerance);
intersects = t > tTolerance && t < 1 - tTolerance && ...
    u > uTolerance && u < 1 - uTolerance;
end

function value = cross2(first, second)
value = first(1) * second(2) - first(2) * second(1);
end

function invalidAssembly()
error('duallink5:validation:InvalidAssemblyTopology', ...
    'Assemblies must contain finite complete assembly points.');
end
