function tf = segmentsIntersect(p1, p2, q1, q2, tolerance)
o1 = cross2(p2 - p1, q1 - p1);
o2 = cross2(p2 - p1, q2 - p1);
o3 = cross2(q2 - q1, p1 - q1);
o4 = cross2(q2 - q1, p2 - q1);
pOrientationTolerance = tolerance * ...
    max(norm(p2 - p1), tolerance);
qOrientationTolerance = tolerance * ...
    max(norm(q2 - q1), tolerance);

properCrossing = ...
    ((o1 > pOrientationTolerance && o2 < -pOrientationTolerance) || ...
     (o1 < -pOrientationTolerance && o2 > pOrientationTolerance)) && ...
    ((o3 > qOrientationTolerance && o4 < -qOrientationTolerance) || ...
     (o3 < -qOrientationTolerance && o4 > qOrientationTolerance));
tf = properCrossing || ...
    (abs(o1) <= pOrientationTolerance && ...
        onSegment(p1, p2, q1, tolerance)) || ...
    (abs(o2) <= pOrientationTolerance && ...
        onSegment(p1, p2, q2, tolerance)) || ...
    (abs(o3) <= qOrientationTolerance && ...
        onSegment(q1, q2, p1, tolerance)) || ...
    (abs(o4) <= qOrientationTolerance && ...
        onSegment(q1, q2, p2, tolerance));
end

function tf = onSegment(a, b, point, tolerance)
tf = all(point >= min(a, b) - tolerance) && ...
    all(point <= max(a, b) + tolerance);
end

function value = cross2(a, b)
value = a(1) * b(2) - a(2) * b(1);
end
